- assetId: adv_pstory_001_cmmn_before-hard-final-normal-01
  produceType: ProduceType_FirstStar
  title: 追い込みレッスン開始！
  type: ProduceAdvType_BeforeFinalLessonHard
- assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
  produceType: ProduceType_FirstStar
  title: 追い込みレッスン開始！
  type: ProduceAdvType_BeforeMid1LessonHard
- assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
  produceType: ProduceType_FirstStar
  title: 追い込みレッスン開始！
  type: ProduceAdvType_BeforeMid2LessonHard
- assetId: adv_produce-refresh_001_before-audition-final
  produceType: ProduceType_FirstStar
  title: 最終試験前日
  type: ProduceAdvType_BeforeFinalAuditionRefresh
- assetId: adv_produce-refresh_001_before-audition-mid
  produceType: ProduceType_FirstStar
  title: 中間試験前日
  type: ProduceAdvType_BeforeMid1AuditionRefresh
- assetId: adv_produce-refresh_001_before-audition-mid
  produceType: ProduceType_FirstStar
  title: 中間試験前日
  type: ProduceAdvType_BeforeMid2AuditionRefresh
- assetId: adv_pstory_001_cmmn_world-explanation
  produceType: ProduceType_FirstStar
  title: 定期公演『初』
  type: ProduceAdvType_Opening
- assetId: adv_presult_001_final-true
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultTrueEnd
- assetId: adv_presult_001_final-normal-01
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultA
- assetId: adv_presult_001_final-normal-02
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultB
- assetId: adv_presult_001_final-normal-03
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultC
- assetId: adv_presult_001_final-failure
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultFailedFinal
- assetId: adv_presult_001_mid-failure
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultFailedMid1
- assetId: adv_presult_001_mid-failure
  produceType: ProduceType_FirstStar
  title: 最終評価は……
  type: ProduceAdvType_ProduceResultFailedMid2