- type: ProduceEffectType_VocalAddition
  name: ボーカル上昇
  produceDescriptionId: ""
- type: ProduceEffectType_DanceAddition
  name: ダンス上昇
  produceDescriptionId: ""
- type: ProduceEffectType_VisualAddition
  name: ビジュアル上昇
  produceDescriptionId: ""
- type: ProduceEffectType_VocalDown
  name: ボーカル低下
  produceDescriptionId: ""
- type: ProduceEffectType_DanceDown
  name: ダンス低下
  produceDescriptionId: ""
- type: ProduceEffectType_VisualDown
  name: ビジュアル低下
  produceDescriptionId: ""
- type: ProduceEffectType_VocalGrowthRateAddition
  name: ボーカルレッスンボーナス+
  produceDescriptionId: ""
- type: ProduceEffectType_DanceGrowthRateAddition
  name: ダンスレッスンボーナス+
  produceDescriptionId: ""
- type: ProduceEffectType_VisualGrowthRateAddition
  name: ビジュアルレッスンボーナス+
  produceDescriptionId: ""
- type: ProduceEffectType_VocalGrowthRateDown
  name: ボーカルレッスンボーナス-
  produceDescriptionId: ""
- type: ProduceEffectType_DanceGrowthRateDown
  name: ダンスレッスンボーナス-
  produceDescriptionId: ""
- type: ProduceEffectType_VisualGrowthRateDown
  name: ビジュアルレッスンボーナス-
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaRecoverFix
  name: 体力回復
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaRecoverMultiple
  name: 体力割合回復
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaReduceFix
  name: 体力減少
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaReduceMultiple
  name: 体力割合減少
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaSpecify
  name: 体力変更
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaRecoverValueUp
  name: 体力回復量増加
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaRecoverValueDown
  name: 体力回復量減少
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaReduceValueUp
  name: 体力減少量増加
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaReduceValueDown
  name: 体力減少量軽減
  produceDescriptionId: ""
- type: ProduceEffectType_StaminaRecoverDisable
  name: 体力回復無効
  produceDescriptionId: ""
- type: ProduceEffectType_MaxStaminaAddition
  name: 最大体力増加
  produceDescriptionId: ""
- type: ProduceEffectType_MaxStaminaReduceFix
  name: 最大体力減少
  produceDescriptionId: ""
- type: ProduceEffectType_MaxStaminaReduceMultiple
  name: 最大体力割合減少
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointReduceFix
  name: Pポイント減少
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointReduceMultiple
  name: Pポイント割合減少
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointSpecify
  name: Pポイント変更
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointAdditionValueUp
  name: Pポイント獲得量増加
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointAdditionValueDown
  name: Pポイント獲得量減少
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointReduceValueUp
  name: Pポイント減少量増加
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointReduceValueDown
  name: Pポイント減少量減少
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceCardUpgrade
  name: 強化
  produceDescriptionId: Label_ProduceCardUpgrade
- type: ProduceEffectType_ProduceCardDuplicate
  name: コピー
  produceDescriptionId: Label_ProduceCardDuplicate
- type: ProduceEffectType_ProduceCardDuplicateUpgrade
  name: コピーして強化
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceCardChange
  name: チェンジ
  produceDescriptionId: Label_ProduceCardChange
- type: ProduceEffectType_ProduceCardChangeUpgrade
  name: チェンジして強化
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceCardDelete
  name: 削除
  produceDescriptionId: Label_ProduceCardDelete
- type: ProduceEffectType_ProducePointAddition
  name: Pポイント獲得
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointGetDisable
  name: Pポイント獲得不可
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceItemGetDisable
  name: Pアイテム獲得不可
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceDrinkGetDisable
  name: Pドリンク獲得不可
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceReward
  name: 報酬獲得
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceRewardSet
  name: 報酬獲得
  produceDescriptionId: ""
- type: ProduceEffectType_AuditionParameterBonusMultiple
  name: スコアボーナス増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonSpChangeRatePermilAddition
  name: SPレッスン発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonVocalSpChangeRatePermilAddition
  name: ボーカルSPレッスン発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonDanceSpChangeRatePermilAddition
  name: ダンスSPレッスン発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonVisualSpChangeRatePermilAddition
  name: ビジュアルSPレッスン発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonSpChangeRatePermilDown
  name: SPレッスン発生率減少
  produceDescriptionId: ""
- type: ProduceEffectType_ExamStatusEnchant
  name: レッスン時発生効果
  produceDescriptionId: ""
- type: ProduceEffectType_LessonPresentProduceCardRewardCountUp
  name: レッスン報酬のスキルカード選択肢追加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonPresentProduceCardRewardCountDown
  name: レッスン報酬のスキルカード選択肢減少
  produceDescriptionId: ""
- type: ProduceEffectType_ShopPriceDiscountMultiple
  name: 相談割引
  produceDescriptionId: ""
- type: ProduceEffectType_ShopProduceCardPriceDiscountMultiple
  name: 相談のスキルカードを割引
  produceDescriptionId: Label_ShopProduceCardPriceDiscountMultiple
- type: ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple
  name: 相談のPドリンクを割引
  produceDescriptionId: ""
- type: ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple
  name: 相談のスキルカード強化を割引
  produceDescriptionId: ""
- type: ProduceEffectType_ShopProduceCardUpgradePriceSpecify
  name: 相談のスキルカード強化を変更
  produceDescriptionId: ""
- type: ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple
  name: 相談のスキルカード削除を割引
  produceDescriptionId: ""
- type: ProduceEffectType_ShopProduceCardDeletePriceSpecify
  name: 相談のスキルカード強化を変更
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceResultRewardMoneyUp
  name: プロデュース完了時の獲得マニー増加
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp
  name: プロデュース完了時のサポートPt増加
  produceDescriptionId: ""
- type: ProduceEffectType_SupportCardEventStaminaRecoverUp
  name: サポートイベントの体力回復量増加
  produceDescriptionId: ""
- type: ProduceEffectType_SupportCardEventProducePointAdditionValueUp
  name: サポートイベントのPポイント獲得量増加
  produceDescriptionId: ""
- type: ProduceEffectType_SupportCardEventParameterAdditionValueUp
  name: サポートイベントのパラメータ上昇量増加
  produceDescriptionId: ""
- type: ProduceEffectType_SupportCardEventProbabilityUp
  name: サポートイベント発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_LessonPresentProducePointUp
  name: レッスン報酬のPポイント獲得量増加
  produceDescriptionId: ""
- type: ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp
  name: レッスンサポート発生率増加
  produceDescriptionId: ""
- type: ProduceEffectType_ProduceCardSelectRerollCountUp
  name: 再抽選回数増加
  produceDescriptionId: ""
- type: ProduceEffectType_ProducePointAdditionDisableTrigger
  name: 初期Pポイント増加
  produceDescriptionId: ""