- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_amao_yes-001_in
  number: 1
  voiceAssetId: sud_vo_system_amao_produce_result-01
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_amao_glad-002_in
  number: 2
  voiceAssetId: sud_vo_system_amao_produce_result-02
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 3
  voiceAssetId: sud_vo_system_amao_produce_result-03
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yaruki-a-001_in
  number: 1
  voiceAssetId: sud_vo_system_amao_produce_result-04
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_amao_glad-001_in
  number: 2
  voiceAssetId: sud_vo_system_amao_produce_result-05
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 3
  voiceAssetId: sud_vo_system_amao_produce_result-06
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_sad-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_amao_produce_result-07
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_amao_produce_result-08
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_sad-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_amao_produce_result-07
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_amao_produce_result-08
- characterId: amao
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_cmmn_kuyashigaru-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_amao_produce_result-09
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_fktn_kobiru-003_in
  number: 1
  voiceAssetId: sud_vo_system_fktn_produce_result-01
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_fktn_kobiru-001_in
  number: 2
  voiceAssetId: sud_vo_system_fktn_produce_result-02
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_fktn_glad-002_in
  number: 3
  voiceAssetId: sud_vo_system_fktn_produce_result-03
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_fktn_glad-001_in
  number: 1
  voiceAssetId: sud_vo_system_fktn_produce_result-04
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_tereru-b-002_in
  number: 2
  voiceAssetId: sud_vo_system_fktn_produce_result-05
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_fktn_yaruki-002_in
  number: 3
  voiceAssetId: sud_vo_system_fktn_produce_result-06
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_glad-b-002_in
  number: 1
  voiceAssetId: sud_vo_system_fktn_produce_result-07
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_fktn_yaruki-003_in
  number: 2
  voiceAssetId: sud_vo_system_fktn_produce_result-08
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_glad-b-002_in
  number: 1
  voiceAssetId: sud_vo_system_fktn_produce_result-07
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_fktn_yaruki-003_in
  number: 2
  voiceAssetId: sud_vo_system_fktn_produce_result-08
- characterId: fktn
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_fktn_angry-001_in
  number: 1
  voiceAssetId: sud_vo_system_fktn_produce_result-09
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_hrnm_glad-002_in
  number: 1
  voiceAssetId: sud_vo_system_hrnm_produce_result-01
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_glad-d-001_in
  number: 2
  voiceAssetId: sud_vo_system_hrnm_produce_result-02
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_hrnm_glad-001_in
  number: 3
  voiceAssetId: sud_vo_system_hrnm_produce_result-03
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_hrnm_produce_result-04
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_hrnm_yaruki-001_in
  number: 2
  voiceAssetId: sud_vo_system_hrnm_produce_result-05
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-002_in
  number: 3
  voiceAssetId: sud_vo_system_hrnm_produce_result-06
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_glad-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_hrnm_produce_result-07
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_think-001_in
  number: 2
  voiceAssetId: sud_vo_system_hrnm_produce_result-08
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_glad-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_hrnm_produce_result-07
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_think-001_in
  number: 2
  voiceAssetId: sud_vo_system_hrnm_produce_result-08
- characterId: hrnm
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_cmmn_sad-002_in
  number: 1
  voiceAssetId: sud_vo_system_hrnm_produce_result-09
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_glad-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_hski_produce_result-01
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_yes-002_in
  number: 2
  voiceAssetId: sud_vo_system_hski_produce_result-02
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_hski_tereru-001_in
  number: 3
  voiceAssetId: sud_vo_system_hski_produce_result-03
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_hski_doya-001_in
  number: 1
  voiceAssetId: sud_vo_system_hski_produce_result-04
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-a-003_in
  number: 2
  voiceAssetId: sud_vo_system_hski_produce_result-05
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-a-001_in
  number: 3
  voiceAssetId: sud_vo_system_hski_produce_result-06
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yes-003_in
  number: 1
  voiceAssetId: sud_vo_system_hski_produce_result-07
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_hski_produce_result-08
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yes-003_in
  number: 1
  voiceAssetId: sud_vo_system_hski_produce_result-07
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_hski_produce_result-08
- characterId: hski
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_cmmn_think-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_hski_produce_result-09
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_ojigi-d-001_in
  number: 1
  voiceAssetId: sud_vo_system_kcna_produce_result-01
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_kcna_glad-001_in
  number: 2
  voiceAssetId: sud_vo_system_kcna_produce_result-02
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_yes-002_in
  number: 3
  voiceAssetId: sud_vo_system_kcna_produce_result-03
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-b-001_in
  number: 1
  voiceAssetId: sud_vo_system_kcna_produce_result-04
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_kcna_tereru-001_in
  number: 2
  voiceAssetId: sud_vo_system_kcna_produce_result-05
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_doya-b-001_in
  number: 3
  voiceAssetId: sud_vo_system_kcna_produce_result-06
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_kcna_yaruki-001_in
  number: 1
  voiceAssetId: sud_vo_system_kcna_produce_result-07
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yaruki-b-001_in
  number: 2
  voiceAssetId: sud_vo_system_kcna_produce_result-08
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_kcna_yaruki-001_in
  number: 1
  voiceAssetId: sud_vo_system_kcna_produce_result-07
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yaruki-b-001_in
  number: 2
  voiceAssetId: sud_vo_system_kcna_produce_result-08
- characterId: kcna
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_kcna_angry-001_in
  number: 1
  voiceAssetId: sud_vo_system_kcna_produce_result-09
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_yes-d-001_in
  number: 1
  voiceAssetId: sud_vo_system_kllj_produce_result-01
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_kllj_glad-001_in
  number: 2
  voiceAssetId: sud_vo_system_kllj_produce_result-02
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_kllj_glad-002_in
  number: 3
  voiceAssetId: sud_vo_system_kllj_produce_result-03
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_glad-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_kllj_produce_result-04
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_glad-d-001_in
  number: 2
  voiceAssetId: sud_vo_system_kllj_produce_result-05
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_kllj_yes-003_in
  number: 3
  voiceAssetId: sud_vo_system_kllj_produce_result-06
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_kllj_produce_result-07
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_sad-002_in
  number: 2
  voiceAssetId: sud_vo_system_kllj_produce_result-08
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_kllj_produce_result-07
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_sad-002_in
  number: 2
  voiceAssetId: sud_vo_system_kllj_produce_result-08
- characterId: kllj
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_kllj_yes-001_in
  number: 1
  voiceAssetId: sud_vo_system_kllj_produce_result-09
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_shro_glad-001_in
  number: 1
  voiceAssetId: sud_vo_system_shro_produce_result-01
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_shro_tereru-001_in
  number: 2
  voiceAssetId: sud_vo_system_shro_produce_result-02
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_shro_tanoshimu-001_in
  number: 3
  voiceAssetId: sud_vo_system_shro_produce_result-03
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_shro_glad-002_in
  number: 1
  voiceAssetId: sud_vo_system_shro_produce_result-04
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_shro_produce_result-05
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_shro_yes-001_in
  number: 3
  voiceAssetId: sud_vo_system_shro_produce_result-06
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yes-004_in
  number: 1
  voiceAssetId: sud_vo_system_shro_produce_result-07
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_shro_produce_result-08
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yes-004_in
  number: 1
  voiceAssetId: sud_vo_system_shro_produce_result-07
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_glad-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_shro_produce_result-08
- characterId: shro
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_shro_yes-001_in
  number: 1
  voiceAssetId: sud_vo_system_shro_produce_result-09
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_cmmn_glad-d-002_in
  number: 1
  voiceAssetId: sud_vo_system_ssmk_produce_result-01
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_ssmk_tanoshimu-001_in
  number: 2
  voiceAssetId: sud_vo_system_ssmk_produce_result-02
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_ssmk_yaruki-001_in
  number: 3
  voiceAssetId: sud_vo_system_ssmk_produce_result-03
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yaruki-a-001_in
  number: 1
  voiceAssetId: sud_vo_system_ssmk_produce_result-04
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_ssmk_kime-001_in
  number: 2
  voiceAssetId: sud_vo_system_ssmk_produce_result-05
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_ssmk_yes-002_in
  number: 3
  voiceAssetId: sud_vo_system_ssmk_produce_result-06
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_yes-a-001_in
  number: 1
  voiceAssetId: sud_vo_system_ssmk_produce_result-07
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_akireru-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_ssmk_produce_result-08
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_yes-a-001_in
  number: 1
  voiceAssetId: sud_vo_system_ssmk_produce_result-07
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_akireru-c-001_in
  number: 2
  voiceAssetId: sud_vo_system_ssmk_produce_result-08
- characterId: ssmk
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_ssmk_produce_result-09
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_ttmr_tereru-001_in
  number: 1
  voiceAssetId: sud_vo_system_ttmr_produce_result-01
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_amao_yes-001_in
  number: 2
  voiceAssetId: sud_vo_system_ttmr_produce_result-02
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_TrueEnd
  motionAssetId: mot_all_chr_ttmr_glad-001_in
  number: 3
  voiceAssetId: sud_vo_system_ttmr_produce_result-03
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_ttmr_produce_result-04
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-a-002_in
  number: 2
  voiceAssetId: sud_vo_system_ttmr_produce_result-05
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_A
  motionAssetId: mot_all_chr_cmmn_yes-a-003_in
  number: 3
  voiceAssetId: sud_vo_system_ttmr_produce_result-06
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_cmmn_sad-004_in
  number: 1
  voiceAssetId: sud_vo_system_ttmr_produce_result-07
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_B
  motionAssetId: mot_all_chr_ttmr_angry-001_in
  number: 2
  voiceAssetId: sud_vo_system_ttmr_produce_result-08
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_cmmn_sad-004_in
  number: 1
  voiceAssetId: sud_vo_system_ttmr_produce_result-07
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_C
  motionAssetId: mot_all_chr_ttmr_angry-001_in
  number: 2
  voiceAssetId: sud_vo_system_ttmr_produce_result-08
- characterId: ttmr
  facialAssetId: ""
  liveType: ProduceLiveType_D
  motionAssetId: mot_all_chr_cmmn_kuyashigaru-c-001_in
  number: 1
  voiceAssetId: sud_vo_system_ttmr_produce_result-09