- continueCount: 3
  examStartAlertStaminaThreshold: 10
  id: p_setting-1
  initialProducePoint: 0
  produceAuditionTrendAssessmentPermil: 200
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
- continueCount: 3
  examStartAlertStaminaThreshold: 10
  id: p_setting-2
  initialProducePoint: 0
  produceAuditionTrendAssessmentPermil: 200
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700