- characterId: amao
  number: 1
  title: 新しい自分
  description: ビジュアル300以上
  vocal: 0
  dance: 0
  visual: 300
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-01
- characterId: amao
  number: 2
  title: 成長できる証
  description: ボーカル450以上
  vocal: 450
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-02
- characterId: amao
  number: 3
  title: 憧れに近づく
  description: ビジュアル1000以上
  vocal: 0
  dance: 0
  visual: 1000
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-03
- characterId: fktn
  number: 1
  title: 生活改善
  description: ダンス300以上
  vocal: 0
  dance: 300
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-01
- characterId: fktn
  number: 2
  title: 才気煥発
  description: ビジュアル450以上
  vocal: 0
  dance: 0
  visual: 450
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-02
- characterId: fktn
  number: 3
  title: 信じる力
  description: ダンス1000以上
  vocal: 0
  dance: 1000
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-03
- characterId: hrnm
  number: 1
  title: 3年生の実力
  description: ボーカル200以上
  vocal: 200
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-01
- characterId: hrnm
  number: 2
  title: もう一度夢を掴むため
  description: ダンス450以上
  vocal: 0
  dance: 450
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-02
- characterId: hrnm
  number: 3
  title: みんなのお姉さん
  description: ビジュアル1000以上
  vocal: 0
  dance: 0
  visual: 1000
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-03
- characterId: hski
  number: 1
  title: 確実な一歩
  description: ダンス200以上
  vocal: 0
  dance: 200
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-01
- characterId: hski
  number: 2
  title: 全力前進
  description: ボーカル450以上
  vocal: 450
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-02
- characterId: hski
  number: 3
  title: 絶対負けない力
  description: ビジュアル900以上
  vocal: 0
  dance: 0
  visual: 900
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-03
- characterId: kcna
  number: 1
  title: 最初の一歩
  description: ボーカル200以上
  vocal: 200
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-01
- characterId: kcna
  number: 2
  title: 元気可愛いの力
  description: ビジュアル450以上
  vocal: 0
  dance: 0
  visual: 450
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-02
- characterId: kcna
  number: 3
  title: 憧れへの一歩
  description: ダンス1000以上
  vocal: 0
  dance: 1000
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-03
- characterId: kllj
  number: 1
  title: 一歩ずつ少しずつ
  description: ダンス200以上
  vocal: 0
  dance: 200
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-01
- characterId: kllj
  number: 2
  title: 届けるための力
  description: ボーカル450以上
  vocal: 450
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-02
- characterId: kllj
  number: 3
  title: 理想の姿
  description: ビジュアル1000以上
  vocal: 0
  dance: 0
  visual: 1000
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-03
- characterId: shro
  number: 1
  title: 必要な基礎力
  description: ボーカル300以上
  vocal: 300
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-01
- characterId: shro
  number: 2
  title: 踊りきる体力
  description: ダンス450以上
  vocal: 0
  dance: 450
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-02
- characterId: shro
  number: 3
  title: 歌い続ける力
  description: ボーカル1000以上
  vocal: 1000
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-03
- characterId: ssmk
  number: 1
  title: 進むための一歩
  description: ダンス300以上
  vocal: 0
  dance: 300
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-01
- characterId: ssmk
  number: 2
  title: 磨かれた笑顔
  description: ビジュアル450以上
  vocal: 0
  dance: 0
  visual: 450
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-02
- characterId: ssmk
  number: 3
  title: もう一度、踊り出す
  description: ダンス1000以上
  vocal: 0
  dance: 1000
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-03
- characterId: ttmr
  number: 1
  title: 実力発揮
  description: ボーカル200以上
  vocal: 200
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-01
- characterId: ttmr
  number: 2
  title: 弱点克服
  description: ダンス450以上
  vocal: 0
  dance: 450
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-02
- characterId: ttmr
  number: 3
  title: 限界突破
  description: ボーカル1000以上
  vocal: 1000
  dance: 0
  visual: 0
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-03