- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-act-2_009
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-1_005
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-1_007
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-2_012
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-2_014
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_003
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_005
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_011
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_012
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_001
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_002
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_019
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_020
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_021
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_022
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_023
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_001
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_002
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_003
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_030
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_031
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_032
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_033
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_042
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_010
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_029
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_030
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_031
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_008
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_024
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_025
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_034
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_035
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_036
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_037
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_038
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_039
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_040
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_041
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_043
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_006
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_033
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_035
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_036
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_003
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_004
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_027
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_028
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_029
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_045
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_046
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_047
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_048
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_049
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_001
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_038
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_039
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_006
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_009
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_030
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_031
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_032
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_033
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_004
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_008
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_050
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_051
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_052
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_053
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_054
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_055
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_057
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_058
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_002
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_004
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_041
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_042
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_043
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_044
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_003
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_005
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_011
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_012
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_010
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_029
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_030
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_031
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_006
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_033
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_035
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_036
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_001
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_038
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_039
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_002
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_004
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_041
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_042
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_043
  ratio: 1
  upgradeCount: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_044
  ratio: 1
  upgradeCount: 1