- name: 共通
  planDetailProduceDescriptionId: Label_ProducePlanType0
  produceDescriptionId: Label_ProducePlanType0
  type: ProducePlanType_Common
- name: 【センス専用】
  planDetailProduceDescriptionId: Label_ProducePlanType1
  produceDescriptionId: Label_ProduceSkillPlanType1
  type: ProducePlanType_Plan1
- name: 【ロジック専用】
  planDetailProduceDescriptionId: Label_ProducePlanType2
  produceDescriptionId: Label_ProduceSkillPlanType2
  type: ProducePlanType_Plan2