- description: 試験に合格する実力は十分なようですね！
  id: p_navi-produce_group-001-audition
  number: 1
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 2
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 3
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 4
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 5
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 6
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 7
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 8
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 9
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 10
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 11
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 12
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 13
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 14
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 15
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 16
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 17
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 18
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 19
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 20
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-audition
  number: 21
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-audition
  number: 22
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 23
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-audition
  number: 24
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-audition
  number: 25
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 26
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 27
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-audition
  number: 28
- description: |-
    もう少しでしたね！
    カードの使用順を工夫してみましょう
  id: p_navi-produce_group-001-lose
  number: 1
- description: |-
    研修「基礎：好調」で
    基本的な事を学べますよ
  id: p_navi-produce_group-001-lose
  number: 2
- description: |-
    研修「基礎：集中」で
    基本的な事を学べますよ
  id: p_navi-produce_group-001-lose
  number: 3
- description: |-
    研修「基礎：好印象」で
    基本的な事を学べますよ
  id: p_navi-produce_group-001-lose
  number: 4
- description: |-
    研修「基礎：やる気」で
    基本的な事を学べますよ
  id: p_navi-produce_group-001-lose
  number: 5
- description: |-
    親愛度が高くなるとスコアボーナスも
    高くなりますよ
  id: p_navi-produce_group-001-lose
  number: 6
- description: |-
    体力不足になってしまったみたいですね
    体力配分に気をつけてみましょう
  id: p_navi-produce_group-001-lose
  number: 7
- description: |-
    好調状態でスコアボーナスの高い
    ターンにカードを使いましょう
  id: p_navi-produce_group-001-lose
  number: 8
- description: |-
    集中が高い状態でスコアボーナスの
    高いターンにカードを使いましょう
  id: p_navi-produce_group-001-lose
  number: 9
- description: |-
    好印象を多く積むことを
    意識してみましょう
  id: p_navi-produce_group-001-lose
  number: 10
- description: |-
    元気の値に応じてスコアを
    獲得するカードを活用しましょう
  id: p_navi-produce_group-001-lose
  number: 11
- description: |-
    ボーカルに僅かな差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 12
- description: |-
    ダンスに僅かな差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 13
- description: |-
    ビジュアルに僅かな差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 14
- description: |-
    ボーカルに僅かな差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 15
- description: |-
    ダンスに僅かな差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 16
- description: |-
    ビジュアルに僅かな差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 17
- description: |-
    ボーカルに差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 18
- description: |-
    ダンスに差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 19
- description: |-
    ビジュアルに差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 20
- description: |-
    ボーカルに差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 21
- description: |-
    ダンスに差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 22
- description: |-
    ビジュアルに差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 23
- description: |-
    ボーカルに差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 24
- description: |-
    ダンスに差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 25
- description: |-
    ビジュアルに差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 26
- description: |-
    ボーカルに大きな差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 27
- description: |-
    ダンスに大きな差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 28
- description: |-
    ビジュアルに大きな差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 29
- description: |-
    ボーカルに大きな差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 30
- description: |-
    ダンスに大きな差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 31
- description: |-
    ビジュアルに大きな差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 32
- description: |-
    ボーカルに大きな差があったみたいです
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 33
- description: |-
    ダンスに大きな差があったみたいです
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 34
- description: |-
    ビジュアルに大きな差があったみたいです
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう
  id: p_navi-produce_group-001-lose
  number: 35
- description: ""
  id: p_navi-produce_group-001-normal
  number: 1
- description: |-
    実力は十分ですが、
    油断せずに最後の試験に挑みましょう！
  id: p_navi-produce_group-001-normal
  number: 2
- description: |-
    最終試験を突破できる、
    十分な実力がついていますね！
  id: p_navi-produce_group-001-normal
  number: 3
- description: |-
    ボーカルが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 4
- description: |-
    ダンスが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 5
- description: |-
    ビジュアルが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 6
- description: |-
    実力は十分ですが、
    油断せず、試験に挑みましょう！
  id: p_navi-produce_group-001-normal
  number: 7
- description: |-
    実力は十分ですね
    きっと試験は突破できますよ！
  id: p_navi-produce_group-001-normal
  number: 8
- description: |-
    ボーカルが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 9
- description: |-
    ダンスが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 10
- description: |-
    ビジュアルが少し不安ですが、
    まだ勝てる可能性はありますよ
  id: p_navi-produce_group-001-normal
  number: 11
- description: |-
    Pポイントがありますね
    先生に相談して、準備を整えてみませんか？
  id: p_navi-produce_group-001-normal
  number: 12
- description: |-
    素晴らしいですね！
    すでに十分な実力があるようです
  id: p_navi-produce_group-001-normal
  number: 13
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 14
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 15
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 16
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 17
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 18
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 19
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 20
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 21
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 22
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 23
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 24
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 25
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 26
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 27
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 28
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 29
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 30
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 31
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 32
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 33
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 34
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 35
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 36
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 37
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 38
- description: |-
    実力は十分ですね。好成績を狙うには
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです！
  id: p_navi-produce_group-001-normal
  number: 39
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 40
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 41
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 42
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 43
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 44
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 45
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 46
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 47
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 48
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 49
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 50
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 51
- description: |-
    ボーカルが少し足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 52
- description: |-
    ダンスが少し足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 53
- description: |-
    ビジュアルが少し足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 54
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 55
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 56
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 57
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 58
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 59
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 60
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 61
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 62
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 63
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 64
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 65
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 66
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 67
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 68
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 69
- description: |-
    ボーカルが大きく足りていないようですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 70
- description: |-
    ダンスが大きく足りていないようですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 71
- description: |-
    ビジュアルが大きく足りていないようですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-normal
  number: 72
- description: |-
    体力の残りが少ないみたいですよ
    アイドルを休ませてあげましょう
  id: p_navi-produce_group-001-normal
  number: 73
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-tutorial
  number: 1
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンがおすすめです
  id: p_navi-produce_group-001-tutorial
  number: 2
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンがおすすめです
  id: p_navi-produce_group-001-tutorial
  number: 3
- description: |-
    体力の残りが少ないみたいですよ
    アイドルを休ませてあげましょう
  id: p_navi-produce_group-001-tutorial
  number: 4
- description: |-
    ボーカルが足りないみたいですね
    <COLOR_VOCAL>ボーカル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-tutorial-audition
  number: 1
- description: |-
    ダンスが足りないみたいですね
    <COLOR_DANCE>ダンス</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-tutorial-audition
  number: 2
- description: |-
    ビジュアルが足りないみたいですね
    <COLOR_VISUAL>ビジュアル</color>レッスンで強化しましょう！
  id: p_navi-produce_group-001-tutorial-audition
  number: 3
- description: |-
    体力の残りが少ないみたいですよ
    アイドルを休ませてあげましょう
  id: p_navi-produce_group-001-tutorial-audition
  number: 4