- locationType: ProduceScheduleLocationType_ProducerRoom1
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c00
- locationType: ProduceScheduleLocationType_ProducerRoom2
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c01
- locationType: ProduceScheduleLocationType_Classroom
  backgroundAssetId: env_3d_prod_schoolroom-01-00-noon
  sceneLayoutId: schoolroom-01-00-noon-c00
- locationType: ProduceScheduleLocationType_Rooftop
  backgroundAssetId: env_3d_prod_rooftop-01-00-noon
  sceneLayoutId: rooftop-01-00-noon-c00
- locationType: ProduceScheduleLocationType_Courtyard
  backgroundAssetId: env_3d_prod_courtyard-01-00-noon
  sceneLayoutId: courtyard-01-00-noon-c00