- characterId: amao
  type: ProduceLiveType_TrueEnd
  musicId: music-all-amao-001
  thumbnailAssetId: img_general_live_music-all-amao-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_amao_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-amao_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: amao
  type: ProduceLiveType_A
  musicId: music-all-amao-001
  thumbnailAssetId: img_general_live_music-all-amao-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_amao_all-001-amao-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-amao_normal-001
  beforeAdvAssetId: adv_live_amao_001_start-01-01
  afterAdvAssetId: adv_live_amao_001_end-01-01
- characterId: amao
  type: ProduceLiveType_B
  musicId: music-all-amao-001
  thumbnailAssetId: img_general_live_music-all-amao-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_amao_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_amao_001_start-02-01
  afterAdvAssetId: adv_live_amao_001_end-02-01
- characterId: amao
  type: ProduceLiveType_C
  musicId: music-all-amao-001
  thumbnailAssetId: img_general_live_music-all-amao-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_amao_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_amao_001_start-03-01
  afterAdvAssetId: adv_live_amao_001_end-03-01
- characterId: amao
  type: ProduceLiveType_D
  musicId: music-all-amao-001
  thumbnailAssetId: img_general_live_music-all-amao-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_amao_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_amao_001_start-04-01
  afterAdvAssetId: adv_live_amao_001_end-04-01
- characterId: fktn
  type: ProduceLiveType_TrueEnd
  musicId: music-all-fktn-001
  thumbnailAssetId: img_general_live_music-all-fktn-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_fktn_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-fktn_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: fktn
  type: ProduceLiveType_A
  musicId: music-all-fktn-001
  thumbnailAssetId: img_general_live_music-all-fktn-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_fktn_all-001-fktn-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-fktn_normal-001
  beforeAdvAssetId: adv_live_fktn_001_start-01-01
  afterAdvAssetId: adv_live_fktn_001_end-01-01
- characterId: fktn
  type: ProduceLiveType_B
  musicId: music-all-fktn-001
  thumbnailAssetId: img_general_live_music-all-fktn-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_fktn_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_fktn_001_start-02-01
  afterAdvAssetId: adv_live_fktn_001_end-02-01
- characterId: fktn
  type: ProduceLiveType_C
  musicId: music-all-fktn-001
  thumbnailAssetId: img_general_live_music-all-fktn-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_fktn_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_fktn_001_start-03-01
  afterAdvAssetId: adv_live_fktn_001_end-03-01
- characterId: fktn
  type: ProduceLiveType_D
  musicId: music-all-fktn-001
  thumbnailAssetId: img_general_live_music-all-fktn-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_fktn_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_fktn_001_start-04-01
  afterAdvAssetId: adv_live_fktn_001_end-04-02
- characterId: hrnm
  type: ProduceLiveType_TrueEnd
  musicId: music-all-hrnm-001
  thumbnailAssetId: img_general_live_music-all-hrnm-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_hrnm_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-hrnm_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: hrnm
  type: ProduceLiveType_A
  musicId: music-all-hrnm-001
  thumbnailAssetId: img_general_live_music-all-hrnm-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_hrnm_all-001-hrnm-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-hrnm_normal-001
  beforeAdvAssetId: adv_live_hrnm_001_start-01-01
  afterAdvAssetId: adv_live_hrnm_001_end-01-01
- characterId: hrnm
  type: ProduceLiveType_B
  musicId: music-all-hrnm-001
  thumbnailAssetId: img_general_live_music-all-hrnm-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_hrnm_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hrnm_001_start-02-01
  afterAdvAssetId: adv_live_hrnm_001_end-02-01
- characterId: hrnm
  type: ProduceLiveType_C
  musicId: music-all-hrnm-001
  thumbnailAssetId: img_general_live_music-all-hrnm-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_hrnm_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hrnm_001_start-03-01
  afterAdvAssetId: adv_live_hrnm_001_end-03-01
- characterId: hrnm
  type: ProduceLiveType_D
  musicId: music-all-hrnm-001
  thumbnailAssetId: img_general_live_music-all-hrnm-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_hrnm_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hrnm_001_start-04-01
  afterAdvAssetId: adv_live_hrnm_001_end-04-01
- characterId: hski
  type: ProduceLiveType_TrueEnd
  musicId: music-all-hski-001
  thumbnailAssetId: img_general_live_music-all-hski-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_hski_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-hski_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: hski
  type: ProduceLiveType_A
  musicId: music-all-hski-001
  thumbnailAssetId: img_general_live_music-all-hski-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_hski_all-001-hski-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-hski_normal-001
  beforeAdvAssetId: adv_live_hski_001_start-01-01
  afterAdvAssetId: adv_live_hski_001_end-01-01
- characterId: hski
  type: ProduceLiveType_B
  musicId: music-all-hski-001
  thumbnailAssetId: img_general_live_music-all-hski-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_hski_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hski_001_start-02-01
  afterAdvAssetId: adv_live_hski_001_end-02-01
- characterId: hski
  type: ProduceLiveType_C
  musicId: music-all-hski-001
  thumbnailAssetId: img_general_live_music-all-hski-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_hski_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hski_001_start-03-01
  afterAdvAssetId: adv_live_hski_001_end-03-01
- characterId: hski
  type: ProduceLiveType_D
  musicId: music-all-hski-001
  thumbnailAssetId: img_general_live_music-all-hski-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_hski_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_hski_001_start-04-01
  afterAdvAssetId: adv_live_hski_001_end-04-01
- characterId: kcna
  type: ProduceLiveType_TrueEnd
  musicId: music-all-kcna-001
  thumbnailAssetId: img_general_live_music-all-kcna-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_kcna_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-kcna_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: kcna
  type: ProduceLiveType_A
  musicId: music-all-kcna-001
  thumbnailAssetId: img_general_live_music-all-kcna-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_kcna_all-001-kcna-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-kcna_normal-001
  beforeAdvAssetId: adv_live_kcna_001_start-01-01
  afterAdvAssetId: adv_live_kcna_001_end-01-01
- characterId: kcna
  type: ProduceLiveType_B
  musicId: music-all-kcna-001
  thumbnailAssetId: img_general_live_music-all-kcna-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_kcna_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kcna_001_start-02-01
  afterAdvAssetId: adv_live_kcna_001_end-02-01
- characterId: kcna
  type: ProduceLiveType_C
  musicId: music-all-kcna-001
  thumbnailAssetId: img_general_live_music-all-kcna-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_kcna_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kcna_001_start-03-01
  afterAdvAssetId: adv_live_kcna_001_end-03-01
- characterId: kcna
  type: ProduceLiveType_D
  musicId: music-all-kcna-001
  thumbnailAssetId: img_general_live_music-all-kcna-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_kcna_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kcna_001_start-04-01
  afterAdvAssetId: adv_live_kcna_001_end-04-02
- characterId: kllj
  type: ProduceLiveType_TrueEnd
  musicId: music-all-kllj-001
  thumbnailAssetId: img_general_live_music-all-kllj-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_kllj_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-kllj_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: kllj
  type: ProduceLiveType_A
  musicId: music-all-kllj-001
  thumbnailAssetId: img_general_live_music-all-kllj-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_kllj_all-001-kllj-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-kllj_normal-001
  beforeAdvAssetId: adv_live_kllj_001_start-01-01
  afterAdvAssetId: adv_live_kllj_001_end-01-01
- characterId: kllj
  type: ProduceLiveType_B
  musicId: music-all-kllj-001
  thumbnailAssetId: img_general_live_music-all-kllj-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_kllj_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kllj_001_start-02-01
  afterAdvAssetId: adv_live_kllj_001_end-02-01
- characterId: kllj
  type: ProduceLiveType_C
  musicId: music-all-kllj-001
  thumbnailAssetId: img_general_live_music-all-kllj-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_kllj_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kllj_001_start-03-01
  afterAdvAssetId: adv_live_kllj_001_end-03-01
- characterId: kllj
  type: ProduceLiveType_D
  musicId: music-all-kllj-001
  thumbnailAssetId: img_general_live_music-all-kllj-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_kllj_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_kllj_001_start-04-01
  afterAdvAssetId: adv_live_kllj_001_end-04-01
- characterId: shro
  type: ProduceLiveType_TrueEnd
  musicId: music-all-shro-001
  thumbnailAssetId: img_general_live_music-all-shro-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_shro_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-shro_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: shro
  type: ProduceLiveType_A
  musicId: music-all-shro-001
  thumbnailAssetId: img_general_live_music-all-shro-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_shro_all-001-shro-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-shro_normal-001
  beforeAdvAssetId: adv_live_shro_001_start-01-01
  afterAdvAssetId: adv_live_shro_001_end-01-01
- characterId: shro
  type: ProduceLiveType_B
  musicId: music-all-shro-001
  thumbnailAssetId: img_general_live_music-all-shro-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_shro_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_shro_001_start-02-01
  afterAdvAssetId: adv_live_shro_001_end-02-01
- characterId: shro
  type: ProduceLiveType_C
  musicId: music-all-shro-001
  thumbnailAssetId: img_general_live_music-all-shro-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_shro_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_shro_001_start-03-01
  afterAdvAssetId: adv_live_shro_001_end-03-01
- characterId: shro
  type: ProduceLiveType_D
  musicId: music-all-shro-001
  thumbnailAssetId: img_general_live_music-all-shro-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_shro_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_shro_001_start-04-01
  afterAdvAssetId: adv_live_shro_001_end-04-01
- characterId: ssmk
  type: ProduceLiveType_TrueEnd
  musicId: music-all-ssmk-001
  thumbnailAssetId: img_general_live_music-all-ssmk-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_ssmk_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-ssmk_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: ssmk
  type: ProduceLiveType_A
  musicId: music-all-ssmk-001
  thumbnailAssetId: img_general_live_music-all-ssmk-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_ssmk_all-001-ssmk-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-ssmk_normal-001
  beforeAdvAssetId: adv_live_ssmk_001_start-01-01
  afterAdvAssetId: adv_live_ssmk_001_end-01-01
- characterId: ssmk
  type: ProduceLiveType_B
  musicId: music-all-ssmk-001
  thumbnailAssetId: img_general_live_music-all-ssmk-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_ssmk_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ssmk_001_start-02-01
  afterAdvAssetId: adv_live_ssmk_001_end-02-01
- characterId: ssmk
  type: ProduceLiveType_C
  musicId: music-all-ssmk-001
  thumbnailAssetId: img_general_live_music-all-ssmk-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_ssmk_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ssmk_001_start-03-01
  afterAdvAssetId: adv_live_ssmk_001_end-03-01
- characterId: ssmk
  type: ProduceLiveType_D
  musicId: music-all-ssmk-001
  thumbnailAssetId: img_general_live_music-all-ssmk-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_ssmk_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ssmk_001_start-04-01
  afterAdvAssetId: adv_live_ssmk_001_end-04-01
- characterId: ttmr
  type: ProduceLiveType_TrueEnd
  musicId: music-all-ttmr-001
  thumbnailAssetId: img_general_live_music-all-ttmr-001_true-end
  environmentAssetId: env_3d_live_all001-00-noon
  timelineAssetId: tln_live_all-001
  motionAssetIds:
  - mot_live_chr_ttmr_all-001_00_in
  liveMusicAssetId: sud_music_live_all-001-ttmr_true-001
  beforeAdvAssetId: ""
  afterAdvAssetId: ""
- characterId: ttmr
  type: ProduceLiveType_A
  musicId: music-all-ttmr-001
  thumbnailAssetId: img_general_live_music-all-ttmr-001_a
  environmentAssetId: env_3d_live_courtyard-00-00-noon
  timelineAssetId: tln_live_cmmn_all-001-normal-001
  motionAssetIds:
  - mot_live_chr_ttmr_all-001-ttmr-normal-001_00_in
  liveMusicAssetId: sud_music_live_all-001-ttmr_normal-001
  beforeAdvAssetId: adv_live_ttmr_001_start-01-01
  afterAdvAssetId: adv_live_ttmr_001_end-01-01
- characterId: ttmr
  type: ProduceLiveType_B
  musicId: music-all-ttmr-001
  thumbnailAssetId: img_general_live_music-all-ttmr-001_b
  environmentAssetId: env_3d_live_rooftop-00-00-noon
  timelineAssetId: tln_live_ttmr_all-001-normal-002
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ttmr_001_start-02-01
  afterAdvAssetId: adv_live_ttmr_001_end-02-01
- characterId: ttmr
  type: ProduceLiveType_C
  musicId: music-all-ttmr-001
  thumbnailAssetId: img_general_live_music-all-ttmr-001_c
  environmentAssetId: env_3d_live_schoolgarden-00-00-noon
  timelineAssetId: tln_live_ttmr_all-001-normal-003
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ttmr_001_start-03-01
  afterAdvAssetId: adv_live_ttmr_001_end-03-01
- characterId: ttmr
  type: ProduceLiveType_D
  musicId: music-all-ttmr-001
  thumbnailAssetId: img_general_live_music-all-ttmr-001_d
  environmentAssetId: env_3d_lesson_danceroom-00-00-noon
  timelineAssetId: tln_live_ttmr_all-001-normal-004
  motionAssetIds: []
  liveMusicAssetId: ""
  beforeAdvAssetId: adv_live_ttmr_001_start-04-01
  afterAdvAssetId: adv_live_ttmr_001_end-04-01