- characterId: amao
  dance: 0
  description: ビジュアル300以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-01
  title: 新しい自分
  visual: 300
  vocal: 0
- characterId: amao
  dance: 0
  description: ボーカル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-02
  title: 成長できる証
  visual: 0
  vocal: 450
- characterId: amao
  dance: 0
  description: ビジュアル1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-amao-fb-03
  title: 憧れに近づく
  visual: 1000
  vocal: 0
- characterId: fktn
  dance: 300
  description: ダンス300以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-01
  title: 生活改善
  visual: 0
  vocal: 0
- characterId: fktn
  dance: 0
  description: ビジュアル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-02
  title: 才気煥発
  visual: 450
  vocal: 0
- characterId: fktn
  dance: 1000
  description: ダンス1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-fktn-fb-03
  title: 信じる力
  visual: 0
  vocal: 0
- characterId: hrnm
  dance: 0
  description: ボーカル200以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-01
  title: 3年生の実力
  visual: 0
  vocal: 200
- characterId: hrnm
  dance: 450
  description: ダンス450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-02
  title: もう一度夢を掴むため
  visual: 0
  vocal: 0
- characterId: hrnm
  dance: 0
  description: ビジュアル1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-hrnm-fb-03
  title: みんなのお姉さん
  visual: 1000
  vocal: 0
- characterId: hski
  dance: 200
  description: ダンス200以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-01
  title: 確実な一歩
  visual: 0
  vocal: 0
- characterId: hski
  dance: 0
  description: ボーカル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-02
  title: 全力前進
  visual: 0
  vocal: 450
- characterId: hski
  dance: 0
  description: ビジュアル900以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-hski-fb-03
  title: 絶対負けない力
  visual: 900
  vocal: 0
- characterId: kcna
  dance: 0
  description: ボーカル200以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-01
  title: 最初の一歩
  visual: 0
  vocal: 200
- characterId: kcna
  dance: 0
  description: ビジュアル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-02
  title: 元気可愛いの力
  visual: 450
  vocal: 0
- characterId: kcna
  dance: 1000
  description: ダンス1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-kcna-fb-03
  title: 憧れへの一歩
  visual: 0
  vocal: 0
- characterId: kllj
  dance: 200
  description: ダンス200以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-01
  title: 一歩ずつ少しずつ
  visual: 0
  vocal: 0
- characterId: kllj
  dance: 0
  description: ボーカル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-02
  title: 届けるための力
  visual: 0
  vocal: 450
- characterId: kllj
  dance: 0
  description: ビジュアル1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-kllj-fb-03
  title: 理想の姿
  visual: 1000
  vocal: 0
- characterId: shro
  dance: 0
  description: ボーカル300以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-01
  title: 必要な基礎力
  visual: 0
  vocal: 300
- characterId: shro
  dance: 450
  description: ダンス450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-02
  title: 踊りきる体力
  visual: 0
  vocal: 0
- characterId: shro
  dance: 0
  description: ボーカル1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-shro-fb-03
  title: 歌い続ける力
  visual: 0
  vocal: 1000
- characterId: ssmk
  dance: 300
  description: ダンス300以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-01
  title: 進むための一歩
  visual: 0
  vocal: 0
- characterId: ssmk
  dance: 0
  description: ビジュアル450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-02
  title: 磨かれた笑顔
  visual: 450
  vocal: 0
- characterId: ssmk
  dance: 1000
  description: ダンス1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-ssmk-fb-03
  title: もう一度、踊り出す
  visual: 0
  vocal: 0
- characterId: ttmr
  dance: 0
  description: ボーカル200以上
  number: 1
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-01
  title: 実力発揮
  visual: 0
  vocal: 200
- characterId: ttmr
  dance: 450
  description: ダンス450以上
  number: 2
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-02
  title: 弱点克服
  visual: 0
  vocal: 0
- characterId: ttmr
  dance: 0
  description: ボーカル1000以上
  number: 3
  produceStepEventDetailId: event-detail-001-p_story-001-ttmr-fb-03
  title: 限界突破
  visual: 0
  vocal: 1000