- characterId: amao
  number: 1
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-01
- characterId: amao
  number: 2
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-02
- characterId: amao
  number: 3
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-c
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-03
- characterId: amao
  number: 4
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-c
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-04
- characterId: amao
  number: 5
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-05
- characterId: amao
  number: 6
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-06
- characterId: amao
  number: 7
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-c
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-07
- characterId: amao
  number: 8
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-c
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-08
- characterId: amao
  number: 9
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-09
- characterId: amao
  number: 10
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-10
- characterId: fktn
  number: 1
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-01
- characterId: fktn
  number: 2
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-02
- characterId: fktn
  number: 3
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-03
- characterId: fktn
  number: 4
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-04
- characterId: fktn
  number: 5
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-05
- characterId: fktn
  number: 6
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-06
- characterId: fktn
  number: 7
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-09
- characterId: fktn
  number: 8
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-08
- characterId: fktn
  number: 9
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-07
- characterId: fktn
  number: 10
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-b
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-10
- characterId: hrnm
  number: 1
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-01
- characterId: hrnm
  number: 2
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-02
- characterId: hrnm
  number: 3
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-03
- characterId: hrnm
  number: 4
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-04
- characterId: hrnm
  number: 5
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-05
- characterId: hrnm
  number: 6
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-06
- characterId: hrnm
  number: 7
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-07
- characterId: hrnm
  number: 8
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-08
- characterId: hrnm
  number: 9
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-09
- characterId: hrnm
  number: 10
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-10
- characterId: hski
  number: 1
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-01
- characterId: hski
  number: 2
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-02
- characterId: hski
  number: 3
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-a
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-03
- characterId: hski
  number: 4
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-a
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-04
- characterId: hski
  number: 5
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-05
- characterId: hski
  number: 6
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-06
- characterId: hski
  number: 7
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-a
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-07
- characterId: hski
  number: 8
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-a
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-08
- characterId: hski
  number: 9
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-09
- characterId: hski
  number: 10
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-10
- characterId: kcna
  number: 1
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-01
- characterId: kcna
  number: 2
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-02
- characterId: kcna
  number: 3
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-03
- characterId: kcna
  number: 4
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-04
- characterId: kcna
  number: 5
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-05
- characterId: kcna
  number: 6
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-06
- characterId: kcna
  number: 7
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-07
- characterId: kcna
  number: 8
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-08
- characterId: kcna
  number: 9
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-09
- characterId: kcna
  number: 10
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-b
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-10
- characterId: kllj
  number: 1
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-01
- characterId: kllj
  number: 2
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-02
- characterId: kllj
  number: 3
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-03
- characterId: kllj
  number: 4
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-04
- characterId: kllj
  number: 5
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-05
- characterId: kllj
  number: 6
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-06
- characterId: kllj
  number: 7
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-07
- characterId: kllj
  number: 8
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-08
- characterId: kllj
  number: 9
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-09
- characterId: kllj
  number: 10
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-10
- characterId: shro
  number: 1
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01-02
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-01
- characterId: shro
  number: 2
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01-02
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-02
- characterId: shro
  number: 3
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-03
- characterId: shro
  number: 4
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-04
- characterId: shro
  number: 5
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-05
- characterId: shro
  number: 6
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-06
- characterId: shro
  number: 7
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-07
- characterId: shro
  number: 8
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-08
- characterId: shro
  number: 9
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-09
- characterId: shro
  number: 10
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-d
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-10
- characterId: ssmk
  number: 1
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-01
- characterId: ssmk
  number: 2
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-02
- characterId: ssmk
  number: 3
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-a
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-03
- characterId: ssmk
  number: 4
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-a
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-04
- characterId: ssmk
  number: 5
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-05
- characterId: ssmk
  number: 6
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-06
- characterId: ssmk
  number: 7
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-a
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-07
- characterId: ssmk
  number: 8
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-a
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-08
- characterId: ssmk
  number: 9
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-09
- characterId: ssmk
  number: 10
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-10
- characterId: ttmr
  number: 1
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01-02
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-01
- characterId: ttmr
  number: 2
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_toschool-01-02
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-02
- characterId: ttmr
  number: 3
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-c-02
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-03
- characterId: ttmr
  number: 4
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_corridor-01-c-02
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-10
- characterId: ttmr
  number: 5
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-05
- characterId: ttmr
  number: 6
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-06
- characterId: ttmr
  number: 7
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-c
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-07
- characterId: ttmr
  number: 8
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-01-c
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-08
- characterId: ttmr
  number: 9
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-09
- characterId: ttmr
  number: 10
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-04