- id: npc_andk
  name: 藍井 撫子
  assetId: exam-audition_andk
- id: npc_mob-da-1
  name: 白崎 あいり
  assetId: exam-audition_mob_01
- id: npc_mob-da-2
  name: 森下 ほのか
  assetId: exam-audition_mob_02
- id: npc_mob-da-3
  name: 汐入 ふうか
  assetId: exam-audition_mob_03
- id: npc_mob-da-4
  name: 久我山 ユリ
  assetId: exam-audition_mob_05
- id: npc_mob-da-5
  name: 蔓日 ユミ
  assetId: exam-audition_mob_04
- id: npc_mob-vi-1
  name: 赤羽 カオリ
  assetId: exam-audition_mob_01
- id: npc_mob-vi-2
  name: 春野 しおり
  assetId: exam-audition_mob_02
- id: npc_mob-vi-3
  name: 前原 まりな
  assetId: exam-audition_mob_03
- id: npc_mob-vi-4
  name: 高円寺 レイ
  assetId: exam-audition_mob_05
- id: npc_mob-vi-5
  name: 蓮田 なな
  assetId: exam-audition_mob_04
- id: npc_mob-vo-1
  name: 四谷 リリ
  assetId: exam-audition_mob_01
- id: npc_mob-vo-2
  name: 石田 リナ
  assetId: exam-audition_mob_02
- id: npc_mob-vo-3
  name: 細川 しずく
  assetId: exam-audition_mob_03
- id: npc_mob-vo-4
  name: 花岡 ミヤビ
  assetId: exam-audition_mob_05
- id: npc_mob-vo-5
  name: 宮地 こはる
  assetId: exam-audition_mob_04
- id: npc_rare-mob-da-1
  name: 暁美 みずき
  assetId: exam-audition_rare-mob_02
- id: npc_rare-mob-da-2
  name: 風間 りおん
  assetId: exam-audition_rare-mob_05
- id: npc_rare-mob-vi-1
  name: 神崎 けい
  assetId: exam-audition_rare-mob_03
- id: npc_rare-mob-vi-2
  name: 華月 ゆりか
  assetId: exam-audition_rare-mob_06
- id: npc_rare-mob-vo-1
  name: 天城 さくら
  assetId: exam-audition_rare-mob_01
- id: npc_rare-mob-vo-2
  name: 鳴海 ひかり
  assetId: exam-audition_rare-mob_04
- id: npc_sgka
  name: 白草 月花
  assetId: exam-audition_sgka
- id: npc_sson
  name: 白草 四音
  assetId: exam-audition_sson