- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-c
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-c
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-c
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-c
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: amao
  costumeHeadId: costume_head_amao-casl-0000
  costumeId: amao-casl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_amao_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-01-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-02-b
  characterId: fktn
  costumeHeadId: costume_head_fktn-casl-0000
  costumeId: fktn-casl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_fktn_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: hrnm
  costumeHeadId: costume_head_hrnm-schl-0000
  costumeId: hrnm-schl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_hrnm_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-a
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-a
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-a
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-a
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: hski
  costumeHeadId: costume_head_hski-schl-0000
  costumeId: hski-schl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_hski_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-b
  characterId: kcna
  costumeHeadId: costume_head_kcna-casl-0000
  costumeId: kcna-casl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_kcna_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: kllj
  costumeHeadId: costume_head_kllj-schl-0000
  costumeId: kllj-schl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_kllj_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01-02
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01-02
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-d
  characterId: shro
  costumeHeadId: costume_head_shro-casl-0000
  costumeId: shro-casl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_shro_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-a
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-a
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-04
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-a
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-a
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: ssmk
  costumeHeadId: costume_head_ssmk-schl-0000
  costumeId: ssmk-schl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_ssmk_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_toschool-01-02
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 1
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-01
- advAssetId: adv_pweek_001_cmmn_toschool-01-02
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 2
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-02
- advAssetId: adv_pweek_001_cmmn_corridor-01-c-02
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 3
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-03
- advAssetId: adv_pweek_001_cmmn_corridor-01-c-02
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 4
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-10
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 5
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-05
- advAssetId: adv_pweek_001_cmmn_schoolroom-01-ac
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 6
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-06
- advAssetId: adv_pweek_001_cmmn_classroom-01-c
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 7
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-07
- advAssetId: adv_pweek_001_cmmn_classroom-01-c
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 8
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-08
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 9
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-09
- advAssetId: adv_pweek_001_cmmn_classroom-02-ac
  characterId: ttmr
  costumeHeadId: costume_head_ttmr-casl-0000
  costumeId: ttmr-casl-0000
  number: 10
  voiceAssetId: sud_vo_system_pweek_ttmr_week-cmmn-04