- level: 1
  totalExp: 0
  unlockTargets: []
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 2
  totalExp: 40
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-1_001
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-1_006
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 3
  totalExp: 160
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-act-2_009
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 4
  totalExp: 430
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-1_025
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-1_032
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 5
  totalExp: 880
  unlockTargets:
  - type: ProducerLevelUnlockType_ShopProduceCardUpgrade
    id: ""
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-3_012
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 6
  totalExp: 1530
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-2_033
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-2_045
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 7
  totalExp: 2380
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-2_042
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_050
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 8
  totalExp: 3430
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_00-2-001
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 9
  totalExp: 4680
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-1_023
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-1_033
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 10
  totalExp: 6130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCardSelectRerollCount
    id: ""
    quantity: 1
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-3_011
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 11
  totalExp: 7780
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-3_030
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-3_001
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 12
  totalExp: 9630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-3_031
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-3_038
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 13
  totalExp: 11730
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-1_020
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-1_003
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 14
  totalExp: 14080
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-1_021
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-1_004
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 15
  totalExp: 16730
  unlockTargets:
  - type: ProducerLevelUnlockType_ShopProduceCardDelete
    id: ""
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_00-3-005
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_00-2-003
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 16
  totalExp: 19680
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-1_007
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-1_005
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 17
  totalExp: 22930
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_034
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_058
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 18
  totalExp: 26480
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_038
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_004
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 19
  totalExp: 30330
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-1_008
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-1_009
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 20
  totalExp: 34530
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_035
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_054
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 21
  totalExp: 39130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_01-2-005
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_02-2-006
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 22
  totalExp: 44130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-2_002
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_052
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 23
  totalExp: 49530
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-2_012
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-2_014
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 24
  totalExp: 55330
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-2_032
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-2_048
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 25
  totalExp: 61630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-3_006
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_002
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 26
  totalExp: 68430
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_01-3-004
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_02-3-007
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 27
  totalExp: 75730
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_01-3-002
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceDrink
    id: pdrink_02-3-006
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 28
  totalExp: 83630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_036
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_008
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 29
  totalExp: 92130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_040
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_051
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 30
  totalExp: 101430
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-3_036
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_004
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 31
  totalExp: 111530
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_037
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 32
  totalExp: 122430
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-2_057
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 33
  totalExp: 134130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-2_001
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 34
  totalExp: 146630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-2_049
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 35
  totalExp: 160130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-3_003
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 36
  totalExp: 174630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-2_041
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 37
  totalExp: 190130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_041
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 38
  totalExp: 206630
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-3_033
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 39
  totalExp: 224130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_044
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 40
  totalExp: 243130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-00-men-3_005
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []
- level: 41
  totalExp: 263130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-3_029
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 42
  totalExp: 284130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_043
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 43
  totalExp: 306130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-act-3_010
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 44
  totalExp: 329130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-act-3_039
    quantity: 0
  reward:
    resourceType: ResourceType_Item
    resourceId: item-staminaregen-1
    quantity: 1
  bonusRewards: []
- level: 45
  totalExp: 354130
  unlockTargets:
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-01-men-3_035
    quantity: 0
  - type: ProducerLevelUnlockType_ProduceCard
    id: p_card-02-men-3_042
    quantity: 0
  reward:
    resourceType: ResourceType_JewelTotal
    resourceId: ""
    quantity: 50
  bonusRewards: []