- id: p_step_lesson_level-001-plan1-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 75
  resultTargetValueLimit: 300
- id: p_step_lesson_level-001-plan1-hard-002
  progressLevel: 1
  limitTurn: 10
  successThreshold: 100
  resultTargetValueLimit: 400
- id: p_step_lesson_level-001-plan1-hard-1
  progressLevel: 1
  limitTurn: 9
  successThreshold: 75
  resultTargetValueLimit: 300
- id: p_step_lesson_level-001-plan1-hard-2
  progressLevel: 1
  limitTurn: 10
  successThreshold: 100
  resultTargetValueLimit: 400
- id: p_step_lesson_level-001-plan1-normal-001
  progressLevel: 1
  limitTurn: 5
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan1-normal-002
  progressLevel: 1
  limitTurn: 5
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan1-normal-003
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-normal-004
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-normal-1
  progressLevel: 1
  limitTurn: 5
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan1-normal-2
  progressLevel: 1
  limitTurn: 5
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan1-normal-3
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-normal-4
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-sp-001
  progressLevel: 1
  limitTurn: 5
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-sp-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan1-sp-003
  progressLevel: 1
  limitTurn: 6
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan1-sp-1
  progressLevel: 1
  limitTurn: 5
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan1-sp-2
  progressLevel: 1
  limitTurn: 6
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan1-sp-3
  progressLevel: 1
  limitTurn: 6
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-aggressive-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 75
  resultTargetValueLimit: 300
- id: p_step_lesson_level-001-plan2-aggressive-hard-002
  progressLevel: 1
  limitTurn: 9
  successThreshold: 100
  resultTargetValueLimit: 400
- id: p_step_lesson_level-001-plan2-aggressive-normal-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-aggressive-normal-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-aggressive-normal-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-aggressive-normal-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-aggressive-sp-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-aggressive-sp-002
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-aggressive-sp-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 75
  resultTargetValueLimit: 300
- id: p_step_lesson_level-001-plan2-hard-002
  progressLevel: 1
  limitTurn: 9
  successThreshold: 100
  resultTargetValueLimit: 400
- id: p_step_lesson_level-001-plan2-hard-1
  progressLevel: 1
  limitTurn: 9
  successThreshold: 75
  resultTargetValueLimit: 300
- id: p_step_lesson_level-001-plan2-hard-2
  progressLevel: 1
  limitTurn: 9
  successThreshold: 100
  resultTargetValueLimit: 400
- id: p_step_lesson_level-001-plan2-normal-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-normal-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-normal-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-normal-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-normal-1
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-normal-2
  progressLevel: 1
  limitTurn: 6
  successThreshold: 25
  resultTargetValueLimit: 50
- id: p_step_lesson_level-001-plan2-normal-3
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-normal-4
  progressLevel: 1
  limitTurn: 7
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-sp-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-sp-002
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-sp-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-sp-1
  progressLevel: 1
  limitTurn: 6
  successThreshold: 40
  resultTargetValueLimit: 80
- id: p_step_lesson_level-001-plan2-sp-2
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-001-plan2-sp-3
  progressLevel: 1
  limitTurn: 7
  successThreshold: 70
  resultTargetValueLimit: 140
- id: p_step_lesson_level-002-plan1-add-1
  progressLevel: 1
  limitTurn: 6
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan1-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 90
  resultTargetValueLimit: 360
- id: p_step_lesson_level-002-plan1-hard-002
  progressLevel: 1
  limitTurn: 12
  successThreshold: 165
  resultTargetValueLimit: 600
- id: p_step_lesson_level-002-plan1-hard-1
  progressLevel: 1
  limitTurn: 9
  successThreshold: 90
  resultTargetValueLimit: 360
- id: p_step_lesson_level-002-plan1-hard-2
  progressLevel: 1
  limitTurn: 12
  successThreshold: 165
  resultTargetValueLimit: 600
- id: p_step_lesson_level-002-plan1-normal-001
  progressLevel: 1
  limitTurn: 5
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan1-normal-002
  progressLevel: 1
  limitTurn: 5
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan1-normal-003
  progressLevel: 1
  limitTurn: 6
  successThreshold: 55
  resultTargetValueLimit: 110
- id: p_step_lesson_level-002-plan1-normal-004
  progressLevel: 1
  limitTurn: 6
  successThreshold: 60
  resultTargetValueLimit: 120
- id: p_step_lesson_level-002-plan1-normal-005
  progressLevel: 1
  limitTurn: 6
  successThreshold: 75
  resultTargetValueLimit: 150
- id: p_step_lesson_level-002-plan1-normal-1
  progressLevel: 1
  limitTurn: 5
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan1-normal-2
  progressLevel: 1
  limitTurn: 5
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan1-normal-3
  progressLevel: 1
  limitTurn: 6
  successThreshold: 55
  resultTargetValueLimit: 110
- id: p_step_lesson_level-002-plan1-normal-4
  progressLevel: 1
  limitTurn: 6
  successThreshold: 60
  resultTargetValueLimit: 120
- id: p_step_lesson_level-002-plan1-normal-5
  progressLevel: 1
  limitTurn: 6
  successThreshold: 75
  resultTargetValueLimit: 150
- id: p_step_lesson_level-002-plan1-school-event
  progressLevel: 1
  limitTurn: 6
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan1-sp-001
  progressLevel: 1
  limitTurn: 5
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan1-sp-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 85
  resultTargetValueLimit: 170
- id: p_step_lesson_level-002-plan1-sp-003
  progressLevel: 1
  limitTurn: 6
  successThreshold: 100
  resultTargetValueLimit: 200
- id: p_step_lesson_level-002-plan1-sp-004
  progressLevel: 1
  limitTurn: 6
  successThreshold: 110
  resultTargetValueLimit: 220
- id: p_step_lesson_level-002-plan1-sp-1
  progressLevel: 1
  limitTurn: 5
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan1-sp-2
  progressLevel: 1
  limitTurn: 6
  successThreshold: 85
  resultTargetValueLimit: 170
- id: p_step_lesson_level-002-plan1-sp-3
  progressLevel: 1
  limitTurn: 6
  successThreshold: 100
  resultTargetValueLimit: 200
- id: p_step_lesson_level-002-plan1-sp-4
  progressLevel: 1
  limitTurn: 6
  successThreshold: 110
  resultTargetValueLimit: 220
- id: p_step_lesson_level-002-plan2-add-1
  progressLevel: 1
  limitTurn: 7
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan2-aggressive-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 90
  resultTargetValueLimit: 360
- id: p_step_lesson_level-002-plan2-aggressive-hard-002
  progressLevel: 1
  limitTurn: 11
  successThreshold: 165
  resultTargetValueLimit: 600
- id: p_step_lesson_level-002-plan2-aggressive-normal-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-aggressive-normal-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-aggressive-normal-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 55
  resultTargetValueLimit: 110
- id: p_step_lesson_level-002-plan2-aggressive-normal-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 60
  resultTargetValueLimit: 120
- id: p_step_lesson_level-002-plan2-aggressive-normal-005
  progressLevel: 1
  limitTurn: 7
  successThreshold: 75
  resultTargetValueLimit: 150
- id: p_step_lesson_level-002-plan2-aggressive-sp-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan2-aggressive-sp-002
  progressLevel: 1
  limitTurn: 7
  successThreshold: 85
  resultTargetValueLimit: 170
- id: p_step_lesson_level-002-plan2-aggressive-sp-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 100
  resultTargetValueLimit: 200
- id: p_step_lesson_level-002-plan2-aggressive-sp-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 110
  resultTargetValueLimit: 220
- id: p_step_lesson_level-002-plan2-hard-001
  progressLevel: 1
  limitTurn: 9
  successThreshold: 90
  resultTargetValueLimit: 360
- id: p_step_lesson_level-002-plan2-hard-002
  progressLevel: 1
  limitTurn: 11
  successThreshold: 165
  resultTargetValueLimit: 600
- id: p_step_lesson_level-002-plan2-hard-1
  progressLevel: 1
  limitTurn: 9
  successThreshold: 90
  resultTargetValueLimit: 360
- id: p_step_lesson_level-002-plan2-hard-2
  progressLevel: 1
  limitTurn: 11
  successThreshold: 165
  resultTargetValueLimit: 600
- id: p_step_lesson_level-002-plan2-normal-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-normal-002
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-normal-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 55
  resultTargetValueLimit: 110
- id: p_step_lesson_level-002-plan2-normal-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 60
  resultTargetValueLimit: 120
- id: p_step_lesson_level-002-plan2-normal-005
  progressLevel: 1
  limitTurn: 7
  successThreshold: 75
  resultTargetValueLimit: 150
- id: p_step_lesson_level-002-plan2-normal-1
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-normal-2
  progressLevel: 1
  limitTurn: 6
  successThreshold: 30
  resultTargetValueLimit: 60
- id: p_step_lesson_level-002-plan2-normal-3
  progressLevel: 1
  limitTurn: 7
  successThreshold: 55
  resultTargetValueLimit: 110
- id: p_step_lesson_level-002-plan2-normal-4
  progressLevel: 1
  limitTurn: 7
  successThreshold: 60
  resultTargetValueLimit: 120
- id: p_step_lesson_level-002-plan2-normal-5
  progressLevel: 1
  limitTurn: 7
  successThreshold: 75
  resultTargetValueLimit: 150
- id: p_step_lesson_level-002-plan2-school-event
  progressLevel: 1
  limitTurn: 7
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan2-sp-001
  progressLevel: 1
  limitTurn: 6
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan2-sp-002
  progressLevel: 1
  limitTurn: 7
  successThreshold: 85
  resultTargetValueLimit: 170
- id: p_step_lesson_level-002-plan2-sp-003
  progressLevel: 1
  limitTurn: 7
  successThreshold: 100
  resultTargetValueLimit: 200
- id: p_step_lesson_level-002-plan2-sp-004
  progressLevel: 1
  limitTurn: 7
  successThreshold: 110
  resultTargetValueLimit: 220
- id: p_step_lesson_level-002-plan2-sp-1
  progressLevel: 1
  limitTurn: 6
  successThreshold: 45
  resultTargetValueLimit: 90
- id: p_step_lesson_level-002-plan2-sp-2
  progressLevel: 1
  limitTurn: 7
  successThreshold: 85
  resultTargetValueLimit: 170
- id: p_step_lesson_level-002-plan2-sp-3
  progressLevel: 1
  limitTurn: 7
  successThreshold: 100
  resultTargetValueLimit: 200
- id: p_step_lesson_level-002-plan2-sp-4
  progressLevel: 1
  limitTurn: 7
  successThreshold: 110
  resultTargetValueLimit: 220
- id: p_step_lesson_level-002-tutorial-fktn-001
  progressLevel: 1
  limitTurn: 3
  successThreshold: 10
  resultTargetValueLimit: 40
- id: p_step_lesson_level-002-tutorial-fktn-002
  progressLevel: 1
  limitTurn: 3
  successThreshold: 25
  resultTargetValueLimit: 70
- id: p_step_lesson_level-002-tutorial-hski-001
  progressLevel: 1
  limitTurn: 3
  successThreshold: 10
  resultTargetValueLimit: 40
- id: p_step_lesson_level-002-tutorial-hski-002
  progressLevel: 1
  limitTurn: 3
  successThreshold: 25
  resultTargetValueLimit: 70
- id: p_step_lesson_level-002-tutorial-ttmr-001
  progressLevel: 1
  limitTurn: 3
  successThreshold: 10
  resultTargetValueLimit: 40
- id: p_step_lesson_level-002-tutorial-ttmr-002
  progressLevel: 1
  limitTurn: 3
  successThreshold: 25
  resultTargetValueLimit: 70