- dance: 168
  id: p_exam_battle_config-davi-01-produce-001-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-001-1
  turn: 9
  visual: 101
  vocal: 67
- dance: 444
  id: p_exam_battle_config-davi-01-produce-001-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-001-2
  turn: 11
  visual: 266
  vocal: 178
- dance: 319
  id: p_exam_battle_config-davi-01-produce-002-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-002-1
  turn: 9
  visual: 191
  vocal: 127
- dance: 953
  id: p_exam_battle_config-davi-01-produce-002-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-002-2
  turn: 11
  visual: 572
  vocal: 381
- dance: 4000
  id: p_exam_battle_config-davi-01-seminar_gruop-03-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-2
  turn: 6
  visual: 2500
  vocal: 2000
- dance: 203
  id: p_exam_battle_config-davi-02-produce-001-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-001-1
  turn: 9
  visual: 78
  vocal: 57
- dance: 535
  id: p_exam_battle_config-davi-02-produce-001-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-001-2
  turn: 12
  visual: 205
  vocal: 152
- dance: 384
  id: p_exam_battle_config-davi-02-produce-002-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-002-1
  turn: 9
  visual: 147
  vocal: 109
- dance: 1149
  id: p_exam_battle_config-davi-02-produce-002-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-002-2
  turn: 12
  visual: 440
  vocal: 326
- dance: 151
  id: p_exam_battle_config-davi-04-produce-001-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-001-1
  turn: 9
  visual: 134
  vocal: 50
- dance: 399
  id: p_exam_battle_config-davi-04-produce-001-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-001-2
  turn: 11
  visual: 355
  vocal: 133
- dance: 286
  id: p_exam_battle_config-davi-04-produce-002-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-002-1
  turn: 9
  visual: 255
  vocal: 95
- dance: 857
  id: p_exam_battle_config-davi-04-produce-002-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-002-2
  turn: 11
  visual: 762
  vocal: 286
- dance: 110
  id: p_exam_battle_config-tutorial_fktn
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-fktn
  turn: 4
  visual: 80
  vocal: 65
- dance: 80
  id: p_exam_battle_config-tutorial_hski
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-hski
  turn: 4
  visual: 110
  vocal: 65
- dance: 80
  id: p_exam_battle_config-tutorial_ttmr
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-ttmr
  turn: 4
  visual: 65
  vocal: 110
- dance: 110
  id: p_exam_battle_config-vida-03-produce-001-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-1
  turn: 9
  visual: 134
  vocal: 90
- dance: 110
  id: p_exam_battle_config-vida-03-produce-001-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-1
  turn: 9
  visual: 134
  vocal: 90
- dance: 291
  id: p_exam_battle_config-vida-03-produce-001-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-2
  turn: 12
  visual: 353
  vocal: 238
- dance: 291
  id: p_exam_battle_config-vida-03-produce-001-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-2
  turn: 11
  visual: 353
  vocal: 238
- dance: 209
  id: p_exam_battle_config-vida-03-produce-002-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-1
  turn: 9
  visual: 253
  vocal: 171
- dance: 209
  id: p_exam_battle_config-vida-03-produce-002-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-1
  turn: 9
  visual: 253
  vocal: 171
- dance: 626
  id: p_exam_battle_config-vida-03-produce-002-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-2
  turn: 12
  visual: 758
  vocal: 512
- dance: 626
  id: p_exam_battle_config-vida-03-produce-002-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-2
  turn: 11
  visual: 758
  vocal: 512
- dance: 2000
  id: p_exam_battle_config-vivo-01-seminar_gruop-03-3
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-3
  turn: 6
  visual: 4000
  vocal: 2500
- dance: 101
  id: p_exam_battle_config-voda-01-produce-001-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-001-1
  turn: 9
  visual: 67
  vocal: 168
- dance: 266
  id: p_exam_battle_config-voda-01-produce-001-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-001-2
  turn: 12
  visual: 178
  vocal: 444
- dance: 191
  id: p_exam_battle_config-voda-01-produce-002-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-002-1
  turn: 9
  visual: 127
  vocal: 319
- dance: 572
  id: p_exam_battle_config-voda-01-produce-002-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-002-2
  turn: 12
  visual: 381
  vocal: 953
- dance: 2500
  id: p_exam_battle_config-voda-01-seminar_gruop-03-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-1
  turn: 6
  visual: 2000
  vocal: 4000
- dance: 2500
  id: p_exam_battle_config-voda-01-seminar_gruop-03-4
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-4
  turn: 6
  visual: 2000
  vocal: 4000
- dance: 110
  id: p_exam_battle_config-voda-03-produce-001-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-001-1
  turn: 9
  visual: 90
  vocal: 134
- dance: 291
  id: p_exam_battle_config-voda-03-produce-001-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-001-2
  turn: 11
  visual: 238
  vocal: 353
- dance: 209
  id: p_exam_battle_config-voda-03-produce-002-1-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-002-1
  turn: 9
  visual: 171
  vocal: 253
- dance: 626
  id: p_exam_battle_config-voda-03-produce-002-2-2
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-002-2
  turn: 11
  visual: 512
  vocal: 758
- dance: 50
  id: p_exam_battle_config-vovi-04-produce-001-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-001-1
  turn: 9
  visual: 134
  vocal: 151
- dance: 133
  id: p_exam_battle_config-vovi-04-produce-001-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-001-2
  turn: 12
  visual: 355
  vocal: 399
- dance: 95
  id: p_exam_battle_config-vovi-04-produce-002-1-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-002-1
  turn: 9
  visual: 255
  vocal: 286
- dance: 286
  id: p_exam_battle_config-vovi-04-produce-002-2-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-002-2
  turn: 12
  visual: 762
  vocal: 857