- supportCardId: s_card-1-0000
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0000-01
- supportCardId: s_card-1-0000
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0000-02
- supportCardId: s_card-1-0001
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0001-01
- supportCardId: s_card-1-0001
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0001-02
- supportCardId: s_card-1-0002
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0002-01
- supportCardId: s_card-1-0002
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0002-02
- supportCardId: s_card-1-0003
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0003-01
- supportCardId: s_card-1-0003
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0003-02
- supportCardId: s_card-1-0004
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0004-01
- supportCardId: s_card-1-0004
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0004-02
- supportCardId: s_card-1-0005
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0005-01
- supportCardId: s_card-1-0005
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0005-02
- supportCardId: s_card-1-0006
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0006-01
- supportCardId: s_card-1-0006
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0006-02
- supportCardId: s_card-1-0007
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0007-01
- supportCardId: s_card-1-0007
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0007-02
- supportCardId: s_card-1-0008
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0008-01
- supportCardId: s_card-1-0008
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0008-02
- supportCardId: s_card-1-0009
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0009-01
- supportCardId: s_card-1-0009
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0009-02
- supportCardId: s_card-1-0010
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0010-01
- supportCardId: s_card-1-0010
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0010-02
- supportCardId: s_card-1-0011
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-1-0011-01
- supportCardId: s_card-1-0011
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-1-0011-02
- supportCardId: s_card-2-0000
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0000-01
- supportCardId: s_card-2-0000
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0000-02
- supportCardId: s_card-2-0001
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0001-01
- supportCardId: s_card-2-0001
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0001-02
- supportCardId: s_card-2-0002
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0002-01
- supportCardId: s_card-2-0002
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0002-02
- supportCardId: s_card-2-0003
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0003-01
- supportCardId: s_card-2-0003
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0003-02
- supportCardId: s_card-2-0004
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0004-01
- supportCardId: s_card-2-0004
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0004-02
- supportCardId: s_card-2-0005
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0005-01
- supportCardId: s_card-2-0005
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0005-02
- supportCardId: s_card-2-0006
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0006-01
- supportCardId: s_card-2-0006
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0006-02
- supportCardId: s_card-2-0007
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0007-01
- supportCardId: s_card-2-0007
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0007-02
- supportCardId: s_card-2-0008
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0008-01
- supportCardId: s_card-2-0008
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0008-02
- supportCardId: s_card-2-0009
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0009-01
- supportCardId: s_card-2-0009
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0009-02
- supportCardId: s_card-2-0010
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0010-01
- supportCardId: s_card-2-0010
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0010-02
- supportCardId: s_card-2-0011
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0011-01
- supportCardId: s_card-2-0011
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0011-02
- supportCardId: s_card-2-0012
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0012-01
- supportCardId: s_card-2-0012
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0012-02
- supportCardId: s_card-2-0013
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0013-01
- supportCardId: s_card-2-0013
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0013-02
- supportCardId: s_card-2-0014
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0014-01
- supportCardId: s_card-2-0014
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0014-02
- supportCardId: s_card-2-0015
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-2-0015-01
- supportCardId: s_card-2-0015
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-2-0015-02
- supportCardId: s_card-3-0000
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0000-01
- supportCardId: s_card-3-0000
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0000-02
- supportCardId: s_card-3-0000
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0000-03
- supportCardId: s_card-3-0001
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0001-01
- supportCardId: s_card-3-0001
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0001-02
- supportCardId: s_card-3-0001
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0001-03
- supportCardId: s_card-3-0002
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0002-01
- supportCardId: s_card-3-0002
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0002-02
- supportCardId: s_card-3-0002
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0002-03
- supportCardId: s_card-3-0003
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0003-01
- supportCardId: s_card-3-0003
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0003-02
- supportCardId: s_card-3-0003
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0003-03
- supportCardId: s_card-3-0004
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0004-01
- supportCardId: s_card-3-0004
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0004-02
- supportCardId: s_card-3-0004
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0004-03
- supportCardId: s_card-3-0005
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0005-01
- supportCardId: s_card-3-0005
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0005-02
- supportCardId: s_card-3-0005
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0005-03
- supportCardId: s_card-3-0006
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0006-01
- supportCardId: s_card-3-0006
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0006-02
- supportCardId: s_card-3-0006
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0006-03
- supportCardId: s_card-3-0007
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0007-01
- supportCardId: s_card-3-0007
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0007-02
- supportCardId: s_card-3-0007
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0007-03
- supportCardId: s_card-3-0008
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0008-01
- supportCardId: s_card-3-0008
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0008-02
- supportCardId: s_card-3-0008
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0008-03
- supportCardId: s_card-3-0009
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0009-01
- supportCardId: s_card-3-0009
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0009-02
- supportCardId: s_card-3-0009
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0009-03
- supportCardId: s_card-3-0010
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0010-01
- supportCardId: s_card-3-0010
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0010-02
- supportCardId: s_card-3-0010
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0010-03
- supportCardId: s_card-3-0011
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0011-01
- supportCardId: s_card-3-0011
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0011-02
- supportCardId: s_card-3-0011
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0011-03
- supportCardId: s_card-3-0012
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0012-01
- supportCardId: s_card-3-0012
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0012-02
- supportCardId: s_card-3-0012
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0012-03
- supportCardId: s_card-3-0013
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0013-01
- supportCardId: s_card-3-0013
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0013-02
- supportCardId: s_card-3-0013
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0013-03
- supportCardId: s_card-3-0014
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0014-01
- supportCardId: s_card-3-0014
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0014-02
- supportCardId: s_card-3-0014
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0014-03
- supportCardId: s_card-3-0015
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0015-01
- supportCardId: s_card-3-0015
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0015-02
- supportCardId: s_card-3-0015
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0015-03
- supportCardId: s_card-3-0017
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0017-01
- supportCardId: s_card-3-0017
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0017-02
- supportCardId: s_card-3-0017
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0017-03
- supportCardId: s_card-3-0018
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0018-01
- supportCardId: s_card-3-0018
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0018-02
- supportCardId: s_card-3-0018
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0018-03
- supportCardId: s_card-3-0019
  number: 1
  supportCardLevel: 1
  produceStepEventDetailId: event-detail-s_card-3-0019-01
- supportCardId: s_card-3-0019
  number: 2
  supportCardLevel: 20
  produceStepEventDetailId: event-detail-s_card-3-0019-02
- supportCardId: s_card-3-0019
  number: 3
  supportCardLevel: 40
  produceStepEventDetailId: event-detail-s_card-3-0019-03