- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-act-2_009
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-1_005
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-1_007
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-2_012
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-2_014
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_003
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_005
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_011
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-00-men-3_012
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_001
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_002
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_019
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_020
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_021
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_022
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-1_023
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_001
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_002
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_003
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_030
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_031
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_032
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_033
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-2_042
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_010
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_029
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_030
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-act-3_031
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_008
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_024
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-1_025
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_034
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_035
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_036
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_037
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_038
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_039
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_040
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_041
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-2_043
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_006
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_033
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_035
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-01-men-3_036
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_003
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_004
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_027
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_028
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-1_029
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_045
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_046
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_047
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_048
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-2_049
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_001
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_038
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-act-3_039
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_006
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_009
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_030
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_031
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_032
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-1_033
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_004
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_008
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_050
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_051
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_052
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_053
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_054
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_055
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_057
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-2_058
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_002
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_004
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_041
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_042
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_043
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-all-upgrade_1
  produceCardId: p_card-02-men-3_044
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_003
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_005
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_011
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-00-men-3_012
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_010
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_029
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_030
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-act-3_031
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_006
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_033
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_035
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-01-men-3_036
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_001
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_038
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-act-3_039
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_002
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_004
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_041
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_042
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_043
  upgradeCount: 1
  ratio: 1
- id: p_random_pool-ssr-upgrade_1
  produceCardId: p_card-02-men-3_044
  upgradeCount: 1
  ratio: 1