- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-amao
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-001-1-1
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2500
  forceEndScore: 0
  id: p_step_audition_difficulty-amao
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-001-2-1
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-2-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-amao
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-002-1-1
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 7100
  forceEndScore: 0
  id: p_step_audition_difficulty-amao
  number: 1
  parameterBaseLine: 450
  produceExamBattleConfigId: p_exam_battle_config-vovi-04-produce-002-2-1
  produceExamBattleNpcGroupId: p_npc_group-amao-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-2-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-fktn
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-001-1-2
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2500
  forceEndScore: 0
  id: p_step_audition_difficulty-fktn
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-001-2-2
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-1-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-fktn
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-002-1-2
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 7100
  forceEndScore: 0
  id: p_step_audition_difficulty-fktn
  number: 1
  parameterBaseLine: 450
  produceExamBattleConfigId: p_exam_battle_config-davi-04-produce-002-2-2
  produceExamBattleNpcGroupId: p_npc_group-fktn-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-1-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-hrnm
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-1
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2450
  forceEndScore: 0
  id: p_step_audition_difficulty-hrnm
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-1
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-hrnm
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-1
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 6950
  forceEndScore: 0
  id: p_step_audition_difficulty-hrnm
  number: 1
  parameterBaseLine: 400
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-1
  produceExamBattleNpcGroupId: p_npc_group-hrnm-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-hski
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-1
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2450
  forceEndScore: 0
  id: p_step_audition_difficulty-hski
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-1
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-1-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-hski
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-1
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 6950
  forceEndScore: 0
  id: p_step_audition_difficulty-hski
  number: 1
  parameterBaseLine: 400
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-1
  produceExamBattleNpcGroupId: p_npc_group-hski-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_parameter_buff-1-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-kcna
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-001-1-2
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2550
  forceEndScore: 0
  id: p_step_audition_difficulty-kcna
  number: 1
  parameterBaseLine: 250
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-001-2-2
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-1-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-kcna
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-002-1-2
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 7300
  forceEndScore: 0
  id: p_step_audition_difficulty-kcna
  number: 1
  parameterBaseLine: 500
  produceExamBattleConfigId: p_exam_battle_config-davi-01-produce-002-2-2
  produceExamBattleNpcGroupId: p_npc_group-kcna-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-1-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-kllj
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-1-2
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2450
  forceEndScore: 0
  id: p_step_audition_difficulty-kllj
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-001-2-2
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-2-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-kllj
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-1-2
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 6950
  forceEndScore: 0
  id: p_step_audition_difficulty-kllj
  number: 1
  parameterBaseLine: 400
  produceExamBattleConfigId: p_exam_battle_config-vida-03-produce-002-2-2
  produceExamBattleNpcGroupId: p_npc_group-kllj-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_review-2-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-shro
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-001-1-2
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2450
  forceEndScore: 0
  id: p_step_audition_difficulty-shro
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-001-2-2
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-2-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-shro
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-002-1-2
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 6950
  forceEndScore: 0
  id: p_step_audition_difficulty-shro
  number: 1
  parameterBaseLine: 400
  produceExamBattleConfigId: p_exam_battle_config-voda-03-produce-002-2-2
  produceExamBattleNpcGroupId: p_npc_group-shro-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_card_play_aggressive-2-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-ssmk
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-001-1-1
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2650
  forceEndScore: 0
  id: p_step_audition_difficulty-ssmk
  number: 1
  parameterBaseLine: 300
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-001-2-1
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-3-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1200
  forceEndScore: 1800
  id: p_step_audition_difficulty-ssmk
  number: 1
  parameterBaseLine: 200
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-002-1-1
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 7650
  forceEndScore: 0
  id: p_step_audition_difficulty-ssmk
  number: 1
  parameterBaseLine: 600
  produceExamBattleConfigId: p_exam_battle_config-davi-02-produce-002-2-1
  produceExamBattleNpcGroupId: p_npc_group-ssmk-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-3-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 600
  forceEndScore: 900
  id: p_step_audition_difficulty-ttmr
  number: 1
  parameterBaseLine: 100
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-001-1-1
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-001-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 2550
  forceEndScore: 0
  id: p_step_audition_difficulty-ttmr
  number: 1
  parameterBaseLine: 250
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-001-2-1
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-001-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-001-produce-audition-final
  produceId: produce-001
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal
- baseScore: 1150
  forceEndScore: 1700
  id: p_step_audition_difficulty-ttmr
  number: 1
  parameterBaseLine: 150
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-002-1-1
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-002-1
  produceExamGimmickEffectGroupId: ""
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionMid1
- baseScore: 7300
  forceEndScore: 0
  id: p_step_audition_difficulty-ttmr
  number: 1
  parameterBaseLine: 500
  produceExamBattleConfigId: p_exam_battle_config-voda-01-produce-002-2-1
  produceExamBattleNpcGroupId: p_npc_group-ttmr-produce-002-2
  produceExamGimmickEffectGroupId: p_e_gim-exam_lesson_buff-2-produce-002-produce-audition-final
  produceId: produce-002
  rankThreshold: 3
  stepType: ProduceStepType_AuditionFinal