- type: ExamPlayType_AutoPlay
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_AutoPlay
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_AutoPlay
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  coefficientPermil: 1000
- type: ExamPlayType_AutoPlay
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  coefficientPermil: 800
- type: ExamPlayType_AutoPlay
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayLesson
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayLesson
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayLesson
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  coefficientPermil: 1000
- type: ExamPlayType_ManualPlayLesson
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayLesson
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayLessonHard
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayLessonHard
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayLessonHard
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  coefficientPermil: 1000
- type: ExamPlayType_ManualPlayLessonHard
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayLessonHard
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayAudition
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayAudition
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  coefficientPermil: 900
- type: ExamPlayType_ManualPlayAudition
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  coefficientPermil: 1000
- type: ExamPlayType_ManualPlayAudition
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  coefficientPermil: 800
- type: ExamPlayType_ManualPlayAudition
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  coefficientPermil: 800