- id: p_step_lesson_level-001-plan1-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 300
  successThreshold: 75
- id: p_step_lesson_level-001-plan1-hard-002
  limitTurn: 10
  progressLevel: 1
  resultTargetValueLimit: 400
  successThreshold: 100
- id: p_step_lesson_level-001-plan1-normal-001
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan1-normal-002
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan1-normal-003
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan1-normal-004
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan1-sp-001
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan1-sp-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-001-plan1-sp-003
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-001-plan2-aggressive-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 300
  successThreshold: 75
- id: p_step_lesson_level-001-plan2-aggressive-hard-002
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 400
  successThreshold: 100
- id: p_step_lesson_level-001-plan2-aggressive-normal-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan2-aggressive-normal-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan2-aggressive-normal-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-aggressive-normal-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-aggressive-sp-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-aggressive-sp-002
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-001-plan2-aggressive-sp-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-001-plan2-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 300
  successThreshold: 75
- id: p_step_lesson_level-001-plan2-hard-002
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 400
  successThreshold: 100
- id: p_step_lesson_level-001-plan2-normal-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan2-normal-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 50
  successThreshold: 25
- id: p_step_lesson_level-001-plan2-normal-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-normal-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-sp-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 80
  successThreshold: 40
- id: p_step_lesson_level-001-plan2-sp-002
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-001-plan2-sp-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 140
  successThreshold: 70
- id: p_step_lesson_level-002-plan1-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 360
  successThreshold: 90
- id: p_step_lesson_level-002-plan1-hard-002
  limitTurn: 12
  progressLevel: 1
  resultTargetValueLimit: 600
  successThreshold: 165
- id: p_step_lesson_level-002-plan1-normal-001
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan1-normal-002
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan1-normal-003
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 110
  successThreshold: 55
- id: p_step_lesson_level-002-plan1-normal-004
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 120
  successThreshold: 60
- id: p_step_lesson_level-002-plan1-normal-005
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 150
  successThreshold: 75
- id: p_step_lesson_level-002-plan1-school-event
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 90
  successThreshold: 45
- id: p_step_lesson_level-002-plan1-sp-001
  limitTurn: 5
  progressLevel: 1
  resultTargetValueLimit: 90
  successThreshold: 45
- id: p_step_lesson_level-002-plan1-sp-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 170
  successThreshold: 85
- id: p_step_lesson_level-002-plan1-sp-003
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 200
  successThreshold: 100
- id: p_step_lesson_level-002-plan1-sp-004
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 220
  successThreshold: 110
- id: p_step_lesson_level-002-plan2-aggressive-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 360
  successThreshold: 90
- id: p_step_lesson_level-002-plan2-aggressive-hard-002
  limitTurn: 11
  progressLevel: 1
  resultTargetValueLimit: 600
  successThreshold: 165
- id: p_step_lesson_level-002-plan2-aggressive-normal-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan2-aggressive-normal-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan2-aggressive-normal-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 110
  successThreshold: 55
- id: p_step_lesson_level-002-plan2-aggressive-normal-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 120
  successThreshold: 60
- id: p_step_lesson_level-002-plan2-aggressive-normal-005
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 150
  successThreshold: 75
- id: p_step_lesson_level-002-plan2-aggressive-sp-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 90
  successThreshold: 45
- id: p_step_lesson_level-002-plan2-aggressive-sp-002
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 170
  successThreshold: 85
- id: p_step_lesson_level-002-plan2-aggressive-sp-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 200
  successThreshold: 100
- id: p_step_lesson_level-002-plan2-aggressive-sp-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 220
  successThreshold: 110
- id: p_step_lesson_level-002-plan2-hard-001
  limitTurn: 9
  progressLevel: 1
  resultTargetValueLimit: 360
  successThreshold: 90
- id: p_step_lesson_level-002-plan2-hard-002
  limitTurn: 11
  progressLevel: 1
  resultTargetValueLimit: 600
  successThreshold: 165
- id: p_step_lesson_level-002-plan2-normal-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan2-normal-002
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 60
  successThreshold: 30
- id: p_step_lesson_level-002-plan2-normal-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 110
  successThreshold: 55
- id: p_step_lesson_level-002-plan2-normal-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 120
  successThreshold: 60
- id: p_step_lesson_level-002-plan2-normal-005
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 150
  successThreshold: 75
- id: p_step_lesson_level-002-plan2-school-event
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 90
  successThreshold: 45
- id: p_step_lesson_level-002-plan2-sp-001
  limitTurn: 6
  progressLevel: 1
  resultTargetValueLimit: 90
  successThreshold: 45
- id: p_step_lesson_level-002-plan2-sp-002
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 170
  successThreshold: 85
- id: p_step_lesson_level-002-plan2-sp-003
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 200
  successThreshold: 100
- id: p_step_lesson_level-002-plan2-sp-004
  limitTurn: 7
  progressLevel: 1
  resultTargetValueLimit: 220
  successThreshold: 110
- id: p_step_lesson_level-002-tutorial-fktn-001
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 40
  successThreshold: 10
- id: p_step_lesson_level-002-tutorial-fktn-002
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 70
  successThreshold: 25
- id: p_step_lesson_level-002-tutorial-hski-001
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 40
  successThreshold: 10
- id: p_step_lesson_level-002-tutorial-hski-002
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 70
  successThreshold: 25
- id: p_step_lesson_level-002-tutorial-ttmr-001
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 40
  successThreshold: 10
- id: p_step_lesson_level-002-tutorial-ttmr-002
  limitTurn: 3
  progressLevel: 1
  resultTargetValueLimit: 70
  successThreshold: 25