- id: p_setting-1
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermil: 200
- id: p_setting-2
  initialProducePoint: 0
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
  examStartAlertStaminaThreshold: 10
  continueCount: 3
  produceAuditionTrendAssessmentPermil: 200