- backgroundAssetId: env_3d_prod_classroom-00-00-noon
  locationType: ProduceScheduleLocationType_ProducerRoom1
  sceneLayoutId: classroom-00-00-noon-c00
- backgroundAssetId: env_3d_prod_classroom-00-00-noon
  locationType: ProduceScheduleLocationType_ProducerRoom2
  sceneLayoutId: classroom-00-00-noon-c01
- backgroundAssetId: env_3d_prod_schoolroom-01-00-noon
  locationType: ProduceScheduleLocationType_Classroom
  sceneLayoutId: schoolroom-01-00-noon-c00
- backgroundAssetId: env_3d_prod_rooftop-01-00-noon
  locationType: ProduceScheduleLocationType_Rooftop
  sceneLayoutId: rooftop-01-00-noon-c00
- backgroundAssetId: env_3d_prod_courtyard-01-00-noon
  locationType: ProduceScheduleLocationType_Courtyard
  sceneLayoutId: courtyard-01-00-noon-c00