- type: ProduceEffectType_VocalAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-vocal
  backgroundAssetId: img_general_icon_produce-effect_bg-vocal
- type: ProduceEffectType_DanceAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-dance
  backgroundAssetId: img_general_icon_produce-effect_bg-dance
- type: ProduceEffectType_VisualAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-visual
  backgroundAssetId: img_general_icon_produce-effect_bg-visual
- type: ProduceEffectType_VocalDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-vocal
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_DanceDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-dance
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_VisualDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-visual
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_VocalGrowthRateAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-vocalgrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-vocal
- type: ProduceEffectType_DanceGrowthRateAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-dancegrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-dance
- type: ProduceEffectType_VisualGrowthRateAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-visualgrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-visual
- type: ProduceEffectType_VocalGrowthRateDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-vocalgrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_DanceGrowthRateDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-dancegrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_VisualGrowthRateDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-visualgrowthrate
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_StaminaRecoverFix
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  backgroundAssetId: img_general_icon_produce-effect_bg-stamina
- type: ProduceEffectType_StaminaRecoverMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminamultiple
  backgroundAssetId: img_general_icon_produce-effect_bg-stamina
- type: ProduceEffectType_StaminaReduceFix
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_StaminaReduceMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminamultiple
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_StaminaSpecify
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  backgroundAssetId: img_general_icon_produce-effect_bg-normal
- type: ProduceEffectType_StaminaRecoverValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  backgroundAssetId: img_general_icon_produce-effect_bg-stamina
- type: ProduceEffectType_StaminaRecoverValueDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_StaminaReduceValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminareducevalue
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_StaminaReduceValueDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminareducevalue
  backgroundAssetId: img_general_icon_produce-effect_bg-stamina
- type: ProduceEffectType_StaminaRecoverDisable
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_MaxStaminaAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-maxstamina
  backgroundAssetId: img_general_icon_produce-effect_bg-stamina
- type: ProduceEffectType_MaxStaminaReduceFix
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-maxstamina
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_MaxStaminaReduceMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-maxstaminamultiple
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ProducePointReduceFix
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ProducePointReduceMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointmultiple
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ProducePointSpecify
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-normal
- type: ProduceEffectType_ProducePointAdditionValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProducePointAdditionValueDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ProducePointReduceValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ProducePointReduceValueDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardUpgrade
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardupgrade
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardDuplicate
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardduplicate
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardDuplicateUpgrade
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardduplicateupgrade
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardChange
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardchange
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardChangeUpgrade
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardchangeupgrade
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardDelete
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecarddelete
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProducePointAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProducePointGetDisable
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceItemGetDisable
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceDrinkGetDisable
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceReward
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceReward
  resourceType: ProduceResourceType_ProduceCard
  iconAssetId: img_general_icon_produce-effect_pict-producerewardcard
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceReward
  resourceType: ProduceResourceType_ProduceDrink
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceReward
  resourceType: ProduceResourceType_ProducePoint
  iconAssetId: img_general_icon_produce-effect_pict-producerewardpoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceRewardSet
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceRewardSet
  resourceType: ProduceResourceType_ProduceCard
  iconAssetId: img_general_icon_produce-effect_pict-producerewardcard
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceRewardSet
  resourceType: ProduceResourceType_ProduceDrink
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceRewardSet
  resourceType: ProduceResourceType_ProducePoint
  iconAssetId: img_general_icon_produce-effect_pict-producerewardpoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_AuditionParameterBonusMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-auditionparameterbonusmultiple
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_LessonSpChangeRatePermilAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-sp
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_LessonVocalSpChangeRatePermilAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-sp
  backgroundAssetId: img_general_icon_produce-effect_bg-vocal
- type: ProduceEffectType_LessonDanceSpChangeRatePermilAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-sp
  backgroundAssetId: img_general_icon_produce-effect_bg-dance
- type: ProduceEffectType_LessonVisualSpChangeRatePermilAddition
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-sp
  backgroundAssetId: img_general_icon_produce-effect_bg-visual
- type: ProduceEffectType_LessonSpChangeRatePermilDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-sp
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ExamStatusEnchant
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-examstatusenchant
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_LessonPresentProduceCardRewardCountUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-lessonpresentproducecardrewardcountup
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_LessonPresentProduceCardRewardCountDown
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-lessonpresentproducecardrewardcountdown
  backgroundAssetId: img_general_icon_produce-effect_bg-negative
- type: ProduceEffectType_ShopPriceDiscountMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceCardPriceDiscountMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceCardUpgradePriceSpecify
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ShopProduceCardDeletePriceSpecify
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-shop
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceResultRewardMoneyUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-money
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardenhancepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_SupportCardEventStaminaRecoverUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventstaminarecover
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_SupportCardEventProducePointAdditionValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventpointrecover
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_SupportCardEventParameterAdditionValueUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventparameterrecover
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_SupportCardEventProbabilityUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventprobability
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_LessonPresentProducePointUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventprobability
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProduceCardSelectRerollCountUp
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producecardselectrerollcount
  backgroundAssetId: img_general_icon_produce-effect_bg-positive
- type: ProduceEffectType_ProducePointAdditionDisableTrigger
  resourceType: ProduceResourceType_Unknown
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  backgroundAssetId: img_general_icon_produce-effect_bg-positive