- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0000-01
  supportCardId: s_card-1-0000
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0000-02
  supportCardId: s_card-1-0000
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0001-01
  supportCardId: s_card-1-0001
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0001-02
  supportCardId: s_card-1-0001
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0002-01
  supportCardId: s_card-1-0002
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0002-02
  supportCardId: s_card-1-0002
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0003-01
  supportCardId: s_card-1-0003
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0003-02
  supportCardId: s_card-1-0003
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0004-01
  supportCardId: s_card-1-0004
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0004-02
  supportCardId: s_card-1-0004
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0005-01
  supportCardId: s_card-1-0005
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0005-02
  supportCardId: s_card-1-0005
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0006-01
  supportCardId: s_card-1-0006
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0006-02
  supportCardId: s_card-1-0006
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0007-01
  supportCardId: s_card-1-0007
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0007-02
  supportCardId: s_card-1-0007
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0008-01
  supportCardId: s_card-1-0008
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0008-02
  supportCardId: s_card-1-0008
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0009-01
  supportCardId: s_card-1-0009
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0009-02
  supportCardId: s_card-1-0009
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0010-01
  supportCardId: s_card-1-0010
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0010-02
  supportCardId: s_card-1-0010
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-1-0011-01
  supportCardId: s_card-1-0011
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-1-0011-02
  supportCardId: s_card-1-0011
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0000-01
  supportCardId: s_card-2-0000
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0000-02
  supportCardId: s_card-2-0000
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0001-01
  supportCardId: s_card-2-0001
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0001-02
  supportCardId: s_card-2-0001
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0002-01
  supportCardId: s_card-2-0002
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0002-02
  supportCardId: s_card-2-0002
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0003-01
  supportCardId: s_card-2-0003
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0003-02
  supportCardId: s_card-2-0003
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0004-01
  supportCardId: s_card-2-0004
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0004-02
  supportCardId: s_card-2-0004
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0005-01
  supportCardId: s_card-2-0005
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0005-02
  supportCardId: s_card-2-0005
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0006-01
  supportCardId: s_card-2-0006
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0006-02
  supportCardId: s_card-2-0006
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0007-01
  supportCardId: s_card-2-0007
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0007-02
  supportCardId: s_card-2-0007
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0008-01
  supportCardId: s_card-2-0008
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0008-02
  supportCardId: s_card-2-0008
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0009-01
  supportCardId: s_card-2-0009
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0009-02
  supportCardId: s_card-2-0009
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0010-01
  supportCardId: s_card-2-0010
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0010-02
  supportCardId: s_card-2-0010
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0011-01
  supportCardId: s_card-2-0011
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0011-02
  supportCardId: s_card-2-0011
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0012-01
  supportCardId: s_card-2-0012
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0012-02
  supportCardId: s_card-2-0012
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0013-01
  supportCardId: s_card-2-0013
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0013-02
  supportCardId: s_card-2-0013
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-2-0014-01
  supportCardId: s_card-2-0014
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-2-0014-02
  supportCardId: s_card-2-0014
  supportCardLevel: 20
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0000-01
  supportCardId: s_card-3-0000
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0000-02
  supportCardId: s_card-3-0000
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0000-03
  supportCardId: s_card-3-0000
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0002-01
  supportCardId: s_card-3-0002
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0002-02
  supportCardId: s_card-3-0002
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0002-03
  supportCardId: s_card-3-0002
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0003-01
  supportCardId: s_card-3-0003
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0003-02
  supportCardId: s_card-3-0003
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0003-03
  supportCardId: s_card-3-0003
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0004-01
  supportCardId: s_card-3-0004
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0004-02
  supportCardId: s_card-3-0004
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0004-03
  supportCardId: s_card-3-0004
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0005-01
  supportCardId: s_card-3-0005
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0005-02
  supportCardId: s_card-3-0005
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0005-03
  supportCardId: s_card-3-0005
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0006-01
  supportCardId: s_card-3-0006
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0006-02
  supportCardId: s_card-3-0006
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0006-03
  supportCardId: s_card-3-0006
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0007-01
  supportCardId: s_card-3-0007
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0007-02
  supportCardId: s_card-3-0007
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0007-03
  supportCardId: s_card-3-0007
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0008-01
  supportCardId: s_card-3-0008
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0008-02
  supportCardId: s_card-3-0008
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0008-03
  supportCardId: s_card-3-0008
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0009-01
  supportCardId: s_card-3-0009
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0009-02
  supportCardId: s_card-3-0009
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0009-03
  supportCardId: s_card-3-0009
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0010-01
  supportCardId: s_card-3-0010
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0010-02
  supportCardId: s_card-3-0010
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0010-03
  supportCardId: s_card-3-0010
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0011-01
  supportCardId: s_card-3-0011
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0011-02
  supportCardId: s_card-3-0011
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0011-03
  supportCardId: s_card-3-0011
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0012-01
  supportCardId: s_card-3-0012
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0012-02
  supportCardId: s_card-3-0012
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0012-03
  supportCardId: s_card-3-0012
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0013-01
  supportCardId: s_card-3-0013
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0013-02
  supportCardId: s_card-3-0013
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0013-03
  supportCardId: s_card-3-0013
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0014-01
  supportCardId: s_card-3-0014
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0014-02
  supportCardId: s_card-3-0014
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0014-03
  supportCardId: s_card-3-0014
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0015-01
  supportCardId: s_card-3-0015
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0015-02
  supportCardId: s_card-3-0015
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0015-03
  supportCardId: s_card-3-0015
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0017-01
  supportCardId: s_card-3-0017
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0017-02
  supportCardId: s_card-3-0017
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0017-03
  supportCardId: s_card-3-0017
  supportCardLevel: 40
- number: 1
  produceStepEventDetailId: event-detail-s_card-3-0019-01
  supportCardId: s_card-3-0019
  supportCardLevel: 1
- number: 2
  produceStepEventDetailId: event-detail-s_card-3-0019-02
  supportCardId: s_card-3-0019
  supportCardLevel: 20
- number: 3
  produceStepEventDetailId: event-detail-s_card-3-0019-03
  supportCardId: s_card-3-0019
  supportCardLevel: 40