- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  type: ExamPlayType_AutoPlay
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  type: ExamPlayType_AutoPlay
- coefficientPermil: 1000
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  type: ExamPlayType_AutoPlay
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  type: ExamPlayType_AutoPlay
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  type: ExamPlayType_AutoPlay
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  type: ExamPlayType_ManualPlayLesson
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  type: ExamPlayType_ManualPlayLesson
- coefficientPermil: 1000
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  type: ExamPlayType_ManualPlayLesson
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  type: ExamPlayType_ManualPlayLesson
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  type: ExamPlayType_ManualPlayLesson
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  type: ExamPlayType_ManualPlayLessonHard
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  type: ExamPlayType_ManualPlayLessonHard
- coefficientPermil: 1000
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  type: ExamPlayType_ManualPlayLessonHard
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  type: ExamPlayType_ManualPlayLessonHard
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  type: ExamPlayType_ManualPlayLessonHard
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-active_skill-playing-0_1
  type: ExamPlayType_ManualPlayAudition
- coefficientPermil: 900
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_card_play-p_card_search-mental_skill-playing-0_1
  type: ExamPlayType_ManualPlayAudition
- coefficientPermil: 1000
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn
  type: ExamPlayType_ManualPlayAudition
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-lesson_buff_up-3
  type: ExamPlayType_ManualPlayAudition
- coefficientPermil: 800
  examStatusEnchantProduceExamTriggerId: e_trigger-exam_end_turn-review_up-3
  type: ExamPlayType_ManualPlayAudition